package base.bill.mapper;

import base.bill.entity.TBillPplicationDestruction;
import base.bill.entity.TBillPplicationDestructionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBillPplicationDestructionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_pplication_destruction
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	long countByExample(TBillPplicationDestructionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_pplication_destruction
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int deleteByExample(TBillPplicationDestructionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_pplication_destruction
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_pplication_destruction
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int insert(TBillPplicationDestruction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_pplication_destruction
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int insertSelective(TBillPplicationDestruction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_pplication_destruction
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	List<TBillPplicationDestruction> selectByExample(TBillPplicationDestructionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_pplication_destruction
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	TBillPplicationDestruction selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_pplication_destruction
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TBillPplicationDestruction record,
			@Param("example") TBillPplicationDestructionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_pplication_destruction
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByExample(@Param("record") TBillPplicationDestruction record,
			@Param("example") TBillPplicationDestructionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_pplication_destruction
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByPrimaryKeySelective(TBillPplicationDestruction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_pplication_destruction
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByPrimaryKey(TBillPplicationDestruction record);
}