package base.bill.mapper;

import base.bill.entity.TBillZgMaintain;
import base.bill.entity.TBillZgMaintainExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import base.bill.entity.vo.BillZgMaintainVO;

public interface TBillZgMaintainMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_zg_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	long countByExample(TBillZgMaintainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_zg_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int deleteByExample(TBillZgMaintainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_zg_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int deleteByPrimaryKey(Integer bill_zg_maintain_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_zg_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int insert(TBillZgMaintain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_zg_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int insertSelective(TBillZgMaintain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_zg_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	List<TBillZgMaintain> selectByExample(TBillZgMaintainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_zg_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	TBillZgMaintain selectByPrimaryKey(Integer bill_zg_maintain_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_zg_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TBillZgMaintain record,
			@Param("example") TBillZgMaintainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_zg_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByExample(@Param("record") TBillZgMaintain record, @Param("example") TBillZgMaintainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_zg_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByPrimaryKeySelective(TBillZgMaintain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_zg_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByPrimaryKey(TBillZgMaintain record);

	/**
	 * 
	 * @描述: 获取票据字轨信息
	 * @方法�?: getBillZgMaintainList
	 * @param aMap
	 * @return
	 * @返回类型 List<TBillZgMaintain>
	 * @创建�? 吴镇�?
	 * @创建时间 2018�?5�?14日下�?2:48:22
	 * @修改�? 吴镇�?
	 * @修改时间 2018�?5�?14日下�?2:48:22
	 * @修改备注
	 * @since
	 * @throws
	 */
	public List<TBillZgMaintain> getBillZgMaintainList(Map<String, Object> aMap);
	
	/**
	 * 
	 * @描述: 根据条件获取票据维护信息
	 * @方法�?: getBillZgMaintainByCon
	 * @param billZgMaintainVO
	 * @return
	 * @返回类型 List<TBillZgMaintain>
	 * @创建�? 吴镇�?
	 * @创建时间 2018�?5�?14日下�?3:06:41
	 * @修改�? 吴镇�?
	 * @修改时间 2018�?5�?14日下�?3:06:41
	 * @修改备注
	 * @since
	 * @throws
	 */
	public List<TBillZgMaintain> getBillZgMaintainByCon(BillZgMaintainVO billZgMaintainVO);
}