package base.bill.mapper;

import base.bill.entity.TBillInfoMaintain;
import base.bill.entity.TBillInfoMaintainExample;
import base.bill.entity.vo.BillInfoMaintainVO;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TBillInfoMaintainMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	long countByExample(TBillInfoMaintainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int deleteByExample(TBillInfoMaintainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int deleteByPrimaryKey(Integer bill_info_maintain_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int insert(TBillInfoMaintain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int insertSelective(TBillInfoMaintain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	List<TBillInfoMaintain> selectByExample(TBillInfoMaintainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	TBillInfoMaintain selectByPrimaryKey(Integer bill_info_maintain_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TBillInfoMaintain record,
			@Param("example") TBillInfoMaintainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByExample(@Param("record") TBillInfoMaintain record, @Param("example") TBillInfoMaintainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByPrimaryKeySelective(TBillInfoMaintain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByPrimaryKey(TBillInfoMaintain record);

	/**
	 * 
	 * @描述: 获取票据维护信息
	 * @方法�?: getNotaxProjectList
	 * @param aMap
	 * @return
	 * @返回类型 List<TBillInfoMaintain>
	 * @创建�? 吴镇�?
	 * @创建时间 2018�?5�?14日下�?2:48:22
	 * @修改�? 吴镇�?
	 * @修改时间 2018�?5�?14日下�?2:48:22
	 * @修改备注
	 * @since
	 * @throws
	 */
	public List<TBillInfoMaintain> getBillZgMaintainList(Map<String, Object> aMap);
	
	/**
	 * 
	 * @描述: 根据条件获取票据维护信息
	 * @方法�?: getNotaxProjectByCon
	 * @param billInfoMaintainVO
	 * @return
	 * @返回类型 List<TBillInfoMaintain>
	 * @创建�? 吴镇�?
	 * @创建时间 2018�?5�?14日下�?3:06:41
	 * @修改�? 吴镇�?
	 * @修改时间 2018�?5�?14日下�?3:06:41
	 * @修改备注
	 * @since
	 * @throws
	 */
	public List<TBillInfoMaintain> getBillInfoMaintainByCon(BillInfoMaintainVO billInfoMaintainVO);
	
	/**
	 * 
	 * @描述:
	 * @方法�?: getBillInfoMaintain
	 * @param bill_type_id
	 * @return
	 * @返回类型 List<TBillInfoMaintain>
	 * @创建�? 吴镇�?
	 * @创建时间 2018�?5�?15日下�?3:17:19
	 * @修改�? 吴镇�?
	 * @修改时间 2018�?5�?15日下�?3:17:19
	 * @修改备注
	 * @since
	 * @throws
	 */
	public List<TBillInfoMaintain> getBillInfoMaintainById(Map<String, Object> aMap);
}