package base.bill.mapper;

import base.bill.entity.TContinbutors;
import base.bill.entity.TContinbutorsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TContinbutorsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_continbutors
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	long countByExample(TContinbutorsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_continbutors
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	int deleteByExample(TContinbutorsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_continbutors
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	int insert(TContinbutors record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_continbutors
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	int insertSelective(TContinbutors record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_continbutors
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	List<TContinbutors> selectByExample(TContinbutorsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_continbutors
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TContinbutors record, @Param("example") TContinbutorsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_continbutors
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	int updateByExample(@Param("record") TContinbutors record, @Param("example") TContinbutorsExample example);
}