package base.bill.mapper;

import base.bill.entity.TFinancial;
import base.bill.entity.TFinancialExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TFinancialMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_financial
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	long countByExample(TFinancialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_financial
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int deleteByExample(TFinancialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_financial
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int deleteByPrimaryKey(Integer financial_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_financial
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int insert(TFinancial record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_financial
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int insertSelective(TFinancial record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_financial
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	List<TFinancial> selectByExample(TFinancialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_financial
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	TFinancial selectByPrimaryKey(Integer financial_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_financial
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TFinancial record, @Param("example") TFinancialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_financial
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByExample(@Param("record") TFinancial record, @Param("example") TFinancialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_financial
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByPrimaryKeySelective(TFinancial record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_financial
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByPrimaryKey(TFinancial record);
}