package base.bill.mapper;

import base.bill.entity.TImposingUnit;
import base.bill.entity.TImposingUnitExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TImposingUnitMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	long countByExample(TImposingUnitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int deleteByExample(TImposingUnitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int deleteByPrimaryKey(Integer imposing_unit_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int insert(TImposingUnit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int insertSelective(TImposingUnit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	List<TImposingUnit> selectByExample(TImposingUnitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	TImposingUnit selectByPrimaryKey(Integer imposing_unit_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TImposingUnit record, @Param("example") TImposingUnitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByExample(@Param("record") TImposingUnit record, @Param("example") TImposingUnitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByPrimaryKeySelective(TImposingUnit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByPrimaryKey(TImposingUnit record);

	/**
	 * 
	 * @描述: 获取执收单位父级
	 * @方法�??: getImposingUnitByParentId
	 * @param imposingUnitVO
	 * @return
	 * @返回类型 List<TImposingUnit>
	 * @创建�?? 吴镇�??
	 * @创建时间 2018�??5�??11日上�??9:35:44
	 * @修改�?? 吴镇�??
	 * @修改时间 2018�??5�??11日上�??9:35:44
	 * @修改备注
	 * @since
	 * @throws
	 */
	public List<TImposingUnit> getImposingUnitByParentId(Integer imposing_unit_id);
	
	/**
	 * 
	 * @描述: 执收单位是否使用
	 * @方法�??: updateImposingUnitIsUse
	 * @param tImposingUnit
	 * @return
	 * @返回类型 int
	 * @创建�?? 吴镇�??
	 * @创建时间 2018�??5�??11日上�??11:11:31
	 * @修改�?? 吴镇�??
	 * @修改时间 2018�??5�??11日上�??11:11:31
	 * @修改备注
	 * @since
	 * @throws
	 */
	public int updateImposingUnitIsUse(TImposingUnit tImposingUnit);
	
	/**
	 * 
	 * @描述: 根据用户中的财政id获取执收单位信息
	 * @方法名: getImposingUnitByUser
	 * @param aMap
	 * @return
	 * @返回类型 List<TImposingUnit>
	 * @创建人 吴镇锡
	 * @创建时间 2018年6月8日上午9:59:01
	 * @修改人 吴镇锡
	 * @修改时间 2018年6月8日上午9:59:01
	 * @修改备注
	 * @since
	 * @throws
	 */
	public List<TImposingUnit> getImposingUnitByUser(Map<String, Object> aMap);
	
	
	/**
	 * 
	 * @描述: 根据征收大厅id获取与执收单位挂接信息
	 * @方法名: getLevyFallImposingUnitByLevyFallId
	 * @param aMap
	 * @return
	 * @返回类型 List<TImposingUnit>
	 * @创建人 吴镇锡
	 * @创建时间 2018年6月8日上午9:59:05
	 * @修改人 吴镇锡
	 * @修改时间 2018年6月8日上午9:59:05
	 * @修改备注
	 * @since
	 * @throws
	 */
	public List<TImposingUnit> getLevyFallImposingUnitByLevyFallId(Map<String, Object> aMap);
}