package base.bill.mapper;

import base.bill.entity.TLevyfallBillInfo;
import base.bill.entity.TLevyfallBillInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TLevyfallBillInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	long countByExample(TLevyfallBillInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int deleteByExample(TLevyfallBillInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int deleteByPrimaryKey(Integer levyfall_bill_info_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int insert(TLevyfallBillInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int insertSelective(TLevyfallBillInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	List<TLevyfallBillInfo> selectByExample(TLevyfallBillInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	TLevyfallBillInfo selectByPrimaryKey(Integer levyfall_bill_info_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TLevyfallBillInfo record,
			@Param("example") TLevyfallBillInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByExample(@Param("record") TLevyfallBillInfo record, @Param("example") TLevyfallBillInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByPrimaryKeySelective(TLevyfallBillInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByPrimaryKey(TLevyfallBillInfo record);
}