package base.bill.mapper;

import base.bill.entity.TLevyfallImposingUnit;
import base.bill.entity.TLevyfallImposingUnitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TLevyfallImposingUnitMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	long countByExample(TLevyfallImposingUnitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int deleteByExample(TLevyfallImposingUnitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int deleteByPrimaryKey(Integer levyfall_imposing_unit_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int insert(TLevyfallImposingUnit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int insertSelective(TLevyfallImposingUnit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	List<TLevyfallImposingUnit> selectByExample(TLevyfallImposingUnitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	TLevyfallImposingUnit selectByPrimaryKey(Integer levyfall_imposing_unit_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TLevyfallImposingUnit record,
			@Param("example") TLevyfallImposingUnitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByExample(@Param("record") TLevyfallImposingUnit record,
			@Param("example") TLevyfallImposingUnitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByPrimaryKeySelective(TLevyfallImposingUnit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_imposing_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByPrimaryKey(TLevyfallImposingUnit record);
}