package base.bill.mapper;

import base.bill.entity.TUnitCompetentDepartment;
import base.bill.entity.TUnitCompetentDepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUnitCompetentDepartmentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_unit_competent_department
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	long countByExample(TUnitCompetentDepartmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_unit_competent_department
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int deleteByExample(TUnitCompetentDepartmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_unit_competent_department
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int deleteByPrimaryKey(Integer unit_competent_department_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_unit_competent_department
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int insert(TUnitCompetentDepartment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_unit_competent_department
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int insertSelective(TUnitCompetentDepartment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_unit_competent_department
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	List<TUnitCompetentDepartment> selectByExample(TUnitCompetentDepartmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_unit_competent_department
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	TUnitCompetentDepartment selectByPrimaryKey(Integer unit_competent_department_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_unit_competent_department
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TUnitCompetentDepartment record,
			@Param("example") TUnitCompetentDepartmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_unit_competent_department
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByExample(@Param("record") TUnitCompetentDepartment record,
			@Param("example") TUnitCompetentDepartmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_unit_competent_department
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByPrimaryKeySelective(TUnitCompetentDepartment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_unit_competent_department
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	int updateByPrimaryKey(TUnitCompetentDepartment record);
}