package com.usersauth.entity;

public class SysPermission {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_permission.id
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_permission.menu_code
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String menu_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_permission.menu_name
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String menu_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_permission.permission_code
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String permission_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_permission.permission_name
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String permission_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_permission.parent_id
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private Integer parent_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_permission.uri
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String uri;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_permission.delete_status
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private Integer delete_status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_permission.status_code
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private Integer status_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_permission.img_uri
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String img_uri;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_permission.icon
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String icon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_permission.sequenc
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String sequenc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_permission.service_token
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String service_token;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.id
	 * @return  the value of sys_permission.id
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.id
	 * @param id  the value for sys_permission.id
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.menu_code
	 * @return  the value of sys_permission.menu_code
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getMenu_code() {
		return menu_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.menu_code
	 * @param menu_code  the value for sys_permission.menu_code
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setMenu_code(String menu_code) {
		this.menu_code = menu_code == null ? null : menu_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.menu_name
	 * @return  the value of sys_permission.menu_name
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getMenu_name() {
		return menu_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.menu_name
	 * @param menu_name  the value for sys_permission.menu_name
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setMenu_name(String menu_name) {
		this.menu_name = menu_name == null ? null : menu_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.permission_code
	 * @return  the value of sys_permission.permission_code
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getPermission_code() {
		return permission_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.permission_code
	 * @param permission_code  the value for sys_permission.permission_code
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setPermission_code(String permission_code) {
		this.permission_code = permission_code == null ? null : permission_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.permission_name
	 * @return  the value of sys_permission.permission_name
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getPermission_name() {
		return permission_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.permission_name
	 * @param permission_name  the value for sys_permission.permission_name
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setPermission_name(String permission_name) {
		this.permission_name = permission_name == null ? null : permission_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.parent_id
	 * @return  the value of sys_permission.parent_id
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public Integer getParent_id() {
		return parent_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.parent_id
	 * @param parent_id  the value for sys_permission.parent_id
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setParent_id(Integer parent_id) {
		this.parent_id = parent_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.uri
	 * @return  the value of sys_permission.uri
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getUri() {
		return uri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.uri
	 * @param uri  the value for sys_permission.uri
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setUri(String uri) {
		this.uri = uri == null ? null : uri.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.delete_status
	 * @return  the value of sys_permission.delete_status
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public Integer getDelete_status() {
		return delete_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.delete_status
	 * @param delete_status  the value for sys_permission.delete_status
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setDelete_status(Integer delete_status) {
		this.delete_status = delete_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.status_code
	 * @return  the value of sys_permission.status_code
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public Integer getStatus_code() {
		return status_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.status_code
	 * @param status_code  the value for sys_permission.status_code
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setStatus_code(Integer status_code) {
		this.status_code = status_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.img_uri
	 * @return  the value of sys_permission.img_uri
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getImg_uri() {
		return img_uri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.img_uri
	 * @param img_uri  the value for sys_permission.img_uri
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setImg_uri(String img_uri) {
		this.img_uri = img_uri == null ? null : img_uri.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.icon
	 * @return  the value of sys_permission.icon
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.icon
	 * @param icon  the value for sys_permission.icon
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setIcon(String icon) {
		this.icon = icon == null ? null : icon.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.sequenc
	 * @return  the value of sys_permission.sequenc
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getSequenc() {
		return sequenc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.sequenc
	 * @param sequenc  the value for sys_permission.sequenc
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setSequenc(String sequenc) {
		this.sequenc = sequenc == null ? null : sequenc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.service_token
	 * @return  the value of sys_permission.service_token
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getService_token() {
		return service_token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.service_token
	 * @param service_token  the value for sys_permission.service_token
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setService_token(String service_token) {
		this.service_token = service_token == null ? null : service_token.trim();
	}
}