package com.usersauth.entity;

import java.util.Date;

public class SysUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.id
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.username
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.password
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.nickname
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.role_id
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private Integer role_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.create_time
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private Date create_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.update_time
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private Date update_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.delete_status
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private Integer delete_status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.login_count
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private Integer login_count;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.telephone
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.email
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.last_login_time
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private Date last_login_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.status_code
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private Integer status_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.reserve1
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String reserve1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.reserve2
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String reserve2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.reserve3
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String reserve3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.reserve4
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String reserve4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.reserve5
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String reserve5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.reserve6
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String reserve6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.reserve7
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String reserve7;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.reserve8
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String reserve8;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.reserve9
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String reserve9;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.reserve10
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String reserve10;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.service_token
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	private String service_token;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.id
	 * @return  the value of sys_user.id
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.id
	 * @param id  the value for sys_user.id
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.username
	 * @return  the value of sys_user.username
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.username
	 * @param username  the value for sys_user.username
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.password
	 * @return  the value of sys_user.password
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.password
	 * @param password  the value for sys_user.password
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.nickname
	 * @return  the value of sys_user.nickname
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.nickname
	 * @param nickname  the value for sys_user.nickname
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname == null ? null : nickname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.role_id
	 * @return  the value of sys_user.role_id
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public Integer getRole_id() {
		return role_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.role_id
	 * @param role_id  the value for sys_user.role_id
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setRole_id(Integer role_id) {
		this.role_id = role_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.create_time
	 * @return  the value of sys_user.create_time
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public Date getCreate_time() {
		return create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.create_time
	 * @param create_time  the value for sys_user.create_time
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.update_time
	 * @return  the value of sys_user.update_time
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public Date getUpdate_time() {
		return update_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.update_time
	 * @param update_time  the value for sys_user.update_time
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.delete_status
	 * @return  the value of sys_user.delete_status
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public Integer getDelete_status() {
		return delete_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.delete_status
	 * @param delete_status  the value for sys_user.delete_status
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setDelete_status(Integer delete_status) {
		this.delete_status = delete_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.login_count
	 * @return  the value of sys_user.login_count
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public Integer getLogin_count() {
		return login_count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.login_count
	 * @param login_count  the value for sys_user.login_count
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setLogin_count(Integer login_count) {
		this.login_count = login_count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.telephone
	 * @return  the value of sys_user.telephone
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.telephone
	 * @param telephone  the value for sys_user.telephone
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone == null ? null : telephone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.email
	 * @return  the value of sys_user.email
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.email
	 * @param email  the value for sys_user.email
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.last_login_time
	 * @return  the value of sys_user.last_login_time
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public Date getLast_login_time() {
		return last_login_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.last_login_time
	 * @param last_login_time  the value for sys_user.last_login_time
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setLast_login_time(Date last_login_time) {
		this.last_login_time = last_login_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.status_code
	 * @return  the value of sys_user.status_code
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public Integer getStatus_code() {
		return status_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.status_code
	 * @param status_code  the value for sys_user.status_code
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setStatus_code(Integer status_code) {
		this.status_code = status_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.reserve1
	 * @return  the value of sys_user.reserve1
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getReserve1() {
		return reserve1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.reserve1
	 * @param reserve1  the value for sys_user.reserve1
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1 == null ? null : reserve1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.reserve2
	 * @return  the value of sys_user.reserve2
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getReserve2() {
		return reserve2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.reserve2
	 * @param reserve2  the value for sys_user.reserve2
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2 == null ? null : reserve2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.reserve3
	 * @return  the value of sys_user.reserve3
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getReserve3() {
		return reserve3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.reserve3
	 * @param reserve3  the value for sys_user.reserve3
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setReserve3(String reserve3) {
		this.reserve3 = reserve3 == null ? null : reserve3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.reserve4
	 * @return  the value of sys_user.reserve4
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getReserve4() {
		return reserve4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.reserve4
	 * @param reserve4  the value for sys_user.reserve4
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setReserve4(String reserve4) {
		this.reserve4 = reserve4 == null ? null : reserve4.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.reserve5
	 * @return  the value of sys_user.reserve5
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getReserve5() {
		return reserve5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.reserve5
	 * @param reserve5  the value for sys_user.reserve5
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setReserve5(String reserve5) {
		this.reserve5 = reserve5 == null ? null : reserve5.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.reserve6
	 * @return  the value of sys_user.reserve6
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getReserve6() {
		return reserve6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.reserve6
	 * @param reserve6  the value for sys_user.reserve6
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setReserve6(String reserve6) {
		this.reserve6 = reserve6 == null ? null : reserve6.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.reserve7
	 * @return  the value of sys_user.reserve7
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getReserve7() {
		return reserve7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.reserve7
	 * @param reserve7  the value for sys_user.reserve7
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setReserve7(String reserve7) {
		this.reserve7 = reserve7 == null ? null : reserve7.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.reserve8
	 * @return  the value of sys_user.reserve8
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getReserve8() {
		return reserve8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.reserve8
	 * @param reserve8  the value for sys_user.reserve8
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setReserve8(String reserve8) {
		this.reserve8 = reserve8 == null ? null : reserve8.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.reserve9
	 * @return  the value of sys_user.reserve9
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getReserve9() {
		return reserve9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.reserve9
	 * @param reserve9  the value for sys_user.reserve9
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setReserve9(String reserve9) {
		this.reserve9 = reserve9 == null ? null : reserve9.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.reserve10
	 * @return  the value of sys_user.reserve10
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getReserve10() {
		return reserve10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.reserve10
	 * @param reserve10  the value for sys_user.reserve10
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setReserve10(String reserve10) {
		this.reserve10 = reserve10 == null ? null : reserve10.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.service_token
	 * @return  the value of sys_user.service_token
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public String getService_token() {
		return service_token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.service_token
	 * @param service_token  the value for sys_user.service_token
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	public void setService_token(String service_token) {
		this.service_token = service_token == null ? null : service_token.trim();
	}
}