package base.bill.entity;

import java.util.Date;

public class RefundApplicationMingxi {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refund_application_mingxi.mingxi_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer mingxi_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refund_application_mingxi.id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refund_application_mingxi.bill_information
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String bill_information;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refund_application_mingxi.reasons_refund
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String reasons_refund;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refund_application_mingxi.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer delete_status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refund_application_mingxi.create_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Date create_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refund_application_mingxi.update_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Date update_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refund_application_mingxi.hold
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String hold;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refund_application_mingxi.mingxi_id
	 * @return  the value of refund_application_mingxi.mingxi_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getMingxi_id() {
		return mingxi_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refund_application_mingxi.mingxi_id
	 * @param mingxi_id  the value for refund_application_mingxi.mingxi_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setMingxi_id(Integer mingxi_id) {
		this.mingxi_id = mingxi_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refund_application_mingxi.id
	 * @return  the value of refund_application_mingxi.id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refund_application_mingxi.id
	 * @param id  the value for refund_application_mingxi.id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refund_application_mingxi.bill_information
	 * @return  the value of refund_application_mingxi.bill_information
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getBill_information() {
		return bill_information;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refund_application_mingxi.bill_information
	 * @param bill_information  the value for refund_application_mingxi.bill_information
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setBill_information(String bill_information) {
		this.bill_information = bill_information == null ? null : bill_information.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refund_application_mingxi.reasons_refund
	 * @return  the value of refund_application_mingxi.reasons_refund
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getReasons_refund() {
		return reasons_refund;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refund_application_mingxi.reasons_refund
	 * @param reasons_refund  the value for refund_application_mingxi.reasons_refund
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setReasons_refund(String reasons_refund) {
		this.reasons_refund = reasons_refund == null ? null : reasons_refund.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refund_application_mingxi.delete_status
	 * @return  the value of refund_application_mingxi.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getDelete_status() {
		return delete_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refund_application_mingxi.delete_status
	 * @param delete_status  the value for refund_application_mingxi.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setDelete_status(Integer delete_status) {
		this.delete_status = delete_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refund_application_mingxi.create_date
	 * @return  the value of refund_application_mingxi.create_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getCreate_date() {
		return create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refund_application_mingxi.create_date
	 * @param create_date  the value for refund_application_mingxi.create_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCreate_date(Date create_date) {
		this.create_date = create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refund_application_mingxi.update_date
	 * @return  the value of refund_application_mingxi.update_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getUpdate_date() {
		return update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refund_application_mingxi.update_date
	 * @param update_date  the value for refund_application_mingxi.update_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setUpdate_date(Date update_date) {
		this.update_date = update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refund_application_mingxi.hold
	 * @return  the value of refund_application_mingxi.hold
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getHold() {
		return hold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refund_application_mingxi.hold
	 * @param hold  the value for refund_application_mingxi.hold
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setHold(String hold) {
		this.hold = hold == null ? null : hold.trim();
	}
}