package base.bill.entity;

import java.util.Date;

import org.jeecgframework.poi.excel.annotation.Excel;
/**
 * 票据缴验申请表
 * @author wangp
 * @time 2018-08-08
 */
public class TBillManagementInspection {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection.id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "票据缴验申请表id", mergeVertical = true, isImportField = "id")
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection.applicant_number
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "申请编号 （根据规则自动生成）", mergeVertical = true, isImportField = "applicant_number")
	private String applicant_number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection.applicant_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "申请日期", mergeVertical = true, isImportField = "applicant_time")
	private Date applicant_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection.examination_endtime
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "缴验截止日期", mergeVertical = true, isImportField = "examination_endtime")
	private Date examination_endtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection.company_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "单位编码", mergeVertical = true, isImportField = "company_code")
	private String company_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection.company_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "单位名称", mergeVertical = true, isImportField = "company_name")
	private String company_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection.operator
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String operator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection.memo
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "备注", mergeVertical = true, isImportField = "memo")
	private String memo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection.report_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "上报状态   1（已上报）  0（未上报）", mergeVertical = true, isImportField = "report_status")
	private Integer report_status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "删除状态", mergeVertical = true, isImportField = "delete_status")
	private Integer delete_status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection.financial_examine_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "财政审核状态（0未审核 1审核通过 2.审核不通过）", mergeVertical = true, isImportField = "financial_examine_status")
	private Integer financial_examine_status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection.create_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "创建日期", mergeVertical = true, isImportField = "create_date")
	private Date create_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection.update_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "更新日期", mergeVertical = true, isImportField = "update_date")
	private Date update_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection.hold
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "备用字段", mergeVertical = true, isImportField = "hold")
	private String hold;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection.id
	 * @return  the value of t_bill_management_inspection.id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection.id
	 * @param id  the value for t_bill_management_inspection.id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection.applicant_number
	 * @return  the value of t_bill_management_inspection.applicant_number
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getApplicant_number() {
		return applicant_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection.applicant_number
	 * @param applicant_number  the value for t_bill_management_inspection.applicant_number
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setApplicant_number(String applicant_number) {
		this.applicant_number = applicant_number == null ? null : applicant_number.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection.applicant_time
	 * @return  the value of t_bill_management_inspection.applicant_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getApplicant_time() {
		return applicant_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection.applicant_time
	 * @param applicant_time  the value for t_bill_management_inspection.applicant_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setApplicant_time(Date applicant_time) {
		this.applicant_time = applicant_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection.examination_endtime
	 * @return  the value of t_bill_management_inspection.examination_endtime
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getExamination_endtime() {
		return examination_endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection.examination_endtime
	 * @param examination_endtime  the value for t_bill_management_inspection.examination_endtime
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setExamination_endtime(Date examination_endtime) {
		this.examination_endtime = examination_endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection.company_code
	 * @return  the value of t_bill_management_inspection.company_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getCompany_code() {
		return company_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection.company_code
	 * @param company_code  the value for t_bill_management_inspection.company_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCompany_code(String company_code) {
		this.company_code = company_code == null ? null : company_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection.company_name
	 * @return  the value of t_bill_management_inspection.company_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getCompany_name() {
		return company_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection.company_name
	 * @param company_name  the value for t_bill_management_inspection.company_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCompany_name(String company_name) {
		this.company_name = company_name == null ? null : company_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection.operator
	 * @return  the value of t_bill_management_inspection.operator
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection.operator
	 * @param operator  the value for t_bill_management_inspection.operator
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setOperator(String operator) {
		this.operator = operator == null ? null : operator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection.memo
	 * @return  the value of t_bill_management_inspection.memo
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection.memo
	 * @param memo  the value for t_bill_management_inspection.memo
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setMemo(String memo) {
		this.memo = memo == null ? null : memo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection.report_status
	 * @return  the value of t_bill_management_inspection.report_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getReport_status() {
		return report_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection.report_status
	 * @param report_status  the value for t_bill_management_inspection.report_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setReport_status(Integer report_status) {
		this.report_status = report_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection.delete_status
	 * @return  the value of t_bill_management_inspection.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getDelete_status() {
		return delete_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection.delete_status
	 * @param delete_status  the value for t_bill_management_inspection.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setDelete_status(Integer delete_status) {
		this.delete_status = delete_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection.financial_examine_status
	 * @return  the value of t_bill_management_inspection.financial_examine_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getFinancial_examine_status() {
		return financial_examine_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection.financial_examine_status
	 * @param financial_examine_status  the value for t_bill_management_inspection.financial_examine_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setFinancial_examine_status(Integer financial_examine_status) {
		this.financial_examine_status = financial_examine_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection.create_date
	 * @return  the value of t_bill_management_inspection.create_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getCreate_date() {
		return create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection.create_date
	 * @param create_date  the value for t_bill_management_inspection.create_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCreate_date(Date create_date) {
		this.create_date = create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection.update_date
	 * @return  the value of t_bill_management_inspection.update_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getUpdate_date() {
		return update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection.update_date
	 * @param update_date  the value for t_bill_management_inspection.update_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setUpdate_date(Date update_date) {
		this.update_date = update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection.hold
	 * @return  the value of t_bill_management_inspection.hold
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getHold() {
		return hold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection.hold
	 * @param hold  the value for t_bill_management_inspection.hold
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setHold(String hold) {
		this.hold = hold == null ? null : hold.trim();
	}
}