package base.bill.entity;

import java.util.Date;
/**
 * 票据管理 明细表
 * @author wangp
 * @time 2018-08-08
 */
public class TBillManagementMingxi {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_mingxi.id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_mingxi.bill_management_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer bill_management_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_mingxi.bill_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String bill_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_mingxi.bill_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String bill_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_mingxi.measurement_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String measurement_unit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_mingxi.measurement_unit_num
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer measurement_unit_num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_mingxi.bill_fenshu
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer bill_fenshu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_mingxi.bill_num
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer bill_num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_mingxi.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer delete_status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_mingxi.memo
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String memo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_mingxi.create_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Date create_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_mingxi.update_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Date update_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_mingxi.hold
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String hold;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_mingxi.id
	 * @return  the value of t_bill_management_mingxi.id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_mingxi.id
	 * @param id  the value for t_bill_management_mingxi.id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_mingxi.bill_management_id
	 * @return  the value of t_bill_management_mingxi.bill_management_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getBill_management_id() {
		return bill_management_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_mingxi.bill_management_id
	 * @param bill_management_id  the value for t_bill_management_mingxi.bill_management_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setBill_management_id(Integer bill_management_id) {
		this.bill_management_id = bill_management_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_mingxi.bill_code
	 * @return  the value of t_bill_management_mingxi.bill_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getBill_code() {
		return bill_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_mingxi.bill_code
	 * @param bill_code  the value for t_bill_management_mingxi.bill_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setBill_code(String bill_code) {
		this.bill_code = bill_code == null ? null : bill_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_mingxi.bill_name
	 * @return  the value of t_bill_management_mingxi.bill_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getBill_name() {
		return bill_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_mingxi.bill_name
	 * @param bill_name  the value for t_bill_management_mingxi.bill_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setBill_name(String bill_name) {
		this.bill_name = bill_name == null ? null : bill_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_mingxi.measurement_unit
	 * @return  the value of t_bill_management_mingxi.measurement_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getMeasurement_unit() {
		return measurement_unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_mingxi.measurement_unit
	 * @param measurement_unit  the value for t_bill_management_mingxi.measurement_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setMeasurement_unit(String measurement_unit) {
		this.measurement_unit = measurement_unit == null ? null : measurement_unit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_mingxi.measurement_unit_num
	 * @return  the value of t_bill_management_mingxi.measurement_unit_num
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getMeasurement_unit_num() {
		return measurement_unit_num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_mingxi.measurement_unit_num
	 * @param measurement_unit_num  the value for t_bill_management_mingxi.measurement_unit_num
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setMeasurement_unit_num(Integer measurement_unit_num) {
		this.measurement_unit_num = measurement_unit_num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_mingxi.bill_fenshu
	 * @return  the value of t_bill_management_mingxi.bill_fenshu
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getBill_fenshu() {
		return bill_fenshu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_mingxi.bill_fenshu
	 * @param bill_fenshu  the value for t_bill_management_mingxi.bill_fenshu
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setBill_fenshu(Integer bill_fenshu) {
		this.bill_fenshu = bill_fenshu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_mingxi.bill_num
	 * @return  the value of t_bill_management_mingxi.bill_num
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getBill_num() {
		return bill_num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_mingxi.bill_num
	 * @param bill_num  the value for t_bill_management_mingxi.bill_num
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setBill_num(Integer bill_num) {
		this.bill_num = bill_num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_mingxi.delete_status
	 * @return  the value of t_bill_management_mingxi.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getDelete_status() {
		return delete_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_mingxi.delete_status
	 * @param delete_status  the value for t_bill_management_mingxi.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setDelete_status(Integer delete_status) {
		this.delete_status = delete_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_mingxi.memo
	 * @return  the value of t_bill_management_mingxi.memo
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_mingxi.memo
	 * @param memo  the value for t_bill_management_mingxi.memo
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setMemo(String memo) {
		this.memo = memo == null ? null : memo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_mingxi.create_date
	 * @return  the value of t_bill_management_mingxi.create_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getCreate_date() {
		return create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_mingxi.create_date
	 * @param create_date  the value for t_bill_management_mingxi.create_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCreate_date(Date create_date) {
		this.create_date = create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_mingxi.update_date
	 * @return  the value of t_bill_management_mingxi.update_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getUpdate_date() {
		return update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_mingxi.update_date
	 * @param update_date  the value for t_bill_management_mingxi.update_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setUpdate_date(Date update_date) {
		this.update_date = update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_mingxi.hold
	 * @return  the value of t_bill_management_mingxi.hold
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getHold() {
		return hold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_mingxi.hold
	 * @param hold  the value for t_bill_management_mingxi.hold
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setHold(String hold) {
		this.hold = hold == null ? null : hold.trim();
	}
}