package base.bill.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TBillManagementInspectionMingxiExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_bill_management_inspection_mingxi
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_bill_management_inspection_mingxi
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_bill_management_inspection_mingxi
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_management_inspection_mingxi
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public TBillManagementInspectionMingxiExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_management_inspection_mingxi
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_management_inspection_mingxi
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_management_inspection_mingxi
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_management_inspection_mingxi
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_management_inspection_mingxi
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_management_inspection_mingxi
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_management_inspection_mingxi
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_management_inspection_mingxi
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_management_inspection_mingxi
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_management_inspection_mingxi
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_bill_management_inspection_mingxi
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andMingxi_idIsNull() {
			addCriterion("mingxi_id is null");
			return (Criteria) this;
		}

		public Criteria andMingxi_idIsNotNull() {
			addCriterion("mingxi_id is not null");
			return (Criteria) this;
		}

		public Criteria andMingxi_idEqualTo(Integer value) {
			addCriterion("mingxi_id =", value, "mingxi_id");
			return (Criteria) this;
		}

		public Criteria andMingxi_idNotEqualTo(Integer value) {
			addCriterion("mingxi_id <>", value, "mingxi_id");
			return (Criteria) this;
		}

		public Criteria andMingxi_idGreaterThan(Integer value) {
			addCriterion("mingxi_id >", value, "mingxi_id");
			return (Criteria) this;
		}

		public Criteria andMingxi_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("mingxi_id >=", value, "mingxi_id");
			return (Criteria) this;
		}

		public Criteria andMingxi_idLessThan(Integer value) {
			addCriterion("mingxi_id <", value, "mingxi_id");
			return (Criteria) this;
		}

		public Criteria andMingxi_idLessThanOrEqualTo(Integer value) {
			addCriterion("mingxi_id <=", value, "mingxi_id");
			return (Criteria) this;
		}

		public Criteria andMingxi_idIn(List<Integer> values) {
			addCriterion("mingxi_id in", values, "mingxi_id");
			return (Criteria) this;
		}

		public Criteria andMingxi_idNotIn(List<Integer> values) {
			addCriterion("mingxi_id not in", values, "mingxi_id");
			return (Criteria) this;
		}

		public Criteria andMingxi_idBetween(Integer value1, Integer value2) {
			addCriterion("mingxi_id between", value1, value2, "mingxi_id");
			return (Criteria) this;
		}

		public Criteria andMingxi_idNotBetween(Integer value1, Integer value2) {
			addCriterion("mingxi_id not between", value1, value2, "mingxi_id");
			return (Criteria) this;
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andBill_codeIsNull() {
			addCriterion("bill_code is null");
			return (Criteria) this;
		}

		public Criteria andBill_codeIsNotNull() {
			addCriterion("bill_code is not null");
			return (Criteria) this;
		}

		public Criteria andBill_codeEqualTo(String value) {
			addCriterion("bill_code =", value, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeNotEqualTo(String value) {
			addCriterion("bill_code <>", value, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeGreaterThan(String value) {
			addCriterion("bill_code >", value, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeGreaterThanOrEqualTo(String value) {
			addCriterion("bill_code >=", value, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeLessThan(String value) {
			addCriterion("bill_code <", value, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeLessThanOrEqualTo(String value) {
			addCriterion("bill_code <=", value, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeLike(String value) {
			addCriterion("bill_code like", value, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeNotLike(String value) {
			addCriterion("bill_code not like", value, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeIn(List<String> values) {
			addCriterion("bill_code in", values, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeNotIn(List<String> values) {
			addCriterion("bill_code not in", values, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeBetween(String value1, String value2) {
			addCriterion("bill_code between", value1, value2, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeNotBetween(String value1, String value2) {
			addCriterion("bill_code not between", value1, value2, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_nameIsNull() {
			addCriterion("bill_name is null");
			return (Criteria) this;
		}

		public Criteria andBill_nameIsNotNull() {
			addCriterion("bill_name is not null");
			return (Criteria) this;
		}

		public Criteria andBill_nameEqualTo(String value) {
			addCriterion("bill_name =", value, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameNotEqualTo(String value) {
			addCriterion("bill_name <>", value, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameGreaterThan(String value) {
			addCriterion("bill_name >", value, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameGreaterThanOrEqualTo(String value) {
			addCriterion("bill_name >=", value, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameLessThan(String value) {
			addCriterion("bill_name <", value, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameLessThanOrEqualTo(String value) {
			addCriterion("bill_name <=", value, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameLike(String value) {
			addCriterion("bill_name like", value, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameNotLike(String value) {
			addCriterion("bill_name not like", value, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameIn(List<String> values) {
			addCriterion("bill_name in", values, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameNotIn(List<String> values) {
			addCriterion("bill_name not in", values, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameBetween(String value1, String value2) {
			addCriterion("bill_name between", value1, value2, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameNotBetween(String value1, String value2) {
			addCriterion("bill_name not between", value1, value2, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_prefixIsNull() {
			addCriterion("bill_prefix is null");
			return (Criteria) this;
		}

		public Criteria andBill_prefixIsNotNull() {
			addCriterion("bill_prefix is not null");
			return (Criteria) this;
		}

		public Criteria andBill_prefixEqualTo(Integer value) {
			addCriterion("bill_prefix =", value, "bill_prefix");
			return (Criteria) this;
		}

		public Criteria andBill_prefixNotEqualTo(Integer value) {
			addCriterion("bill_prefix <>", value, "bill_prefix");
			return (Criteria) this;
		}

		public Criteria andBill_prefixGreaterThan(Integer value) {
			addCriterion("bill_prefix >", value, "bill_prefix");
			return (Criteria) this;
		}

		public Criteria andBill_prefixGreaterThanOrEqualTo(Integer value) {
			addCriterion("bill_prefix >=", value, "bill_prefix");
			return (Criteria) this;
		}

		public Criteria andBill_prefixLessThan(Integer value) {
			addCriterion("bill_prefix <", value, "bill_prefix");
			return (Criteria) this;
		}

		public Criteria andBill_prefixLessThanOrEqualTo(Integer value) {
			addCriterion("bill_prefix <=", value, "bill_prefix");
			return (Criteria) this;
		}

		public Criteria andBill_prefixIn(List<Integer> values) {
			addCriterion("bill_prefix in", values, "bill_prefix");
			return (Criteria) this;
		}

		public Criteria andBill_prefixNotIn(List<Integer> values) {
			addCriterion("bill_prefix not in", values, "bill_prefix");
			return (Criteria) this;
		}

		public Criteria andBill_prefixBetween(Integer value1, Integer value2) {
			addCriterion("bill_prefix between", value1, value2, "bill_prefix");
			return (Criteria) this;
		}

		public Criteria andBill_prefixNotBetween(Integer value1, Integer value2) {
			addCriterion("bill_prefix not between", value1, value2, "bill_prefix");
			return (Criteria) this;
		}

		public Criteria andExamination_typeIsNull() {
			addCriterion("examination_type is null");
			return (Criteria) this;
		}

		public Criteria andExamination_typeIsNotNull() {
			addCriterion("examination_type is not null");
			return (Criteria) this;
		}

		public Criteria andExamination_typeEqualTo(Integer value) {
			addCriterion("examination_type =", value, "examination_type");
			return (Criteria) this;
		}

		public Criteria andExamination_typeNotEqualTo(Integer value) {
			addCriterion("examination_type <>", value, "examination_type");
			return (Criteria) this;
		}

		public Criteria andExamination_typeGreaterThan(Integer value) {
			addCriterion("examination_type >", value, "examination_type");
			return (Criteria) this;
		}

		public Criteria andExamination_typeGreaterThanOrEqualTo(Integer value) {
			addCriterion("examination_type >=", value, "examination_type");
			return (Criteria) this;
		}

		public Criteria andExamination_typeLessThan(Integer value) {
			addCriterion("examination_type <", value, "examination_type");
			return (Criteria) this;
		}

		public Criteria andExamination_typeLessThanOrEqualTo(Integer value) {
			addCriterion("examination_type <=", value, "examination_type");
			return (Criteria) this;
		}

		public Criteria andExamination_typeIn(List<Integer> values) {
			addCriterion("examination_type in", values, "examination_type");
			return (Criteria) this;
		}

		public Criteria andExamination_typeNotIn(List<Integer> values) {
			addCriterion("examination_type not in", values, "examination_type");
			return (Criteria) this;
		}

		public Criteria andExamination_typeBetween(Integer value1, Integer value2) {
			addCriterion("examination_type between", value1, value2, "examination_type");
			return (Criteria) this;
		}

		public Criteria andExamination_typeNotBetween(Integer value1, Integer value2) {
			addCriterion("examination_type not between", value1, value2, "examination_type");
			return (Criteria) this;
		}

		public Criteria andExamination_reasonsIsNull() {
			addCriterion("examination_reasons is null");
			return (Criteria) this;
		}

		public Criteria andExamination_reasonsIsNotNull() {
			addCriterion("examination_reasons is not null");
			return (Criteria) this;
		}

		public Criteria andExamination_reasonsEqualTo(String value) {
			addCriterion("examination_reasons =", value, "examination_reasons");
			return (Criteria) this;
		}

		public Criteria andExamination_reasonsNotEqualTo(String value) {
			addCriterion("examination_reasons <>", value, "examination_reasons");
			return (Criteria) this;
		}

		public Criteria andExamination_reasonsGreaterThan(String value) {
			addCriterion("examination_reasons >", value, "examination_reasons");
			return (Criteria) this;
		}

		public Criteria andExamination_reasonsGreaterThanOrEqualTo(String value) {
			addCriterion("examination_reasons >=", value, "examination_reasons");
			return (Criteria) this;
		}

		public Criteria andExamination_reasonsLessThan(String value) {
			addCriterion("examination_reasons <", value, "examination_reasons");
			return (Criteria) this;
		}

		public Criteria andExamination_reasonsLessThanOrEqualTo(String value) {
			addCriterion("examination_reasons <=", value, "examination_reasons");
			return (Criteria) this;
		}

		public Criteria andExamination_reasonsLike(String value) {
			addCriterion("examination_reasons like", value, "examination_reasons");
			return (Criteria) this;
		}

		public Criteria andExamination_reasonsNotLike(String value) {
			addCriterion("examination_reasons not like", value, "examination_reasons");
			return (Criteria) this;
		}

		public Criteria andExamination_reasonsIn(List<String> values) {
			addCriterion("examination_reasons in", values, "examination_reasons");
			return (Criteria) this;
		}

		public Criteria andExamination_reasonsNotIn(List<String> values) {
			addCriterion("examination_reasons not in", values, "examination_reasons");
			return (Criteria) this;
		}

		public Criteria andExamination_reasonsBetween(String value1, String value2) {
			addCriterion("examination_reasons between", value1, value2, "examination_reasons");
			return (Criteria) this;
		}

		public Criteria andExamination_reasonsNotBetween(String value1, String value2) {
			addCriterion("examination_reasons not between", value1, value2, "examination_reasons");
			return (Criteria) this;
		}

		public Criteria andExamination_timeIsNull() {
			addCriterion("examination_time is null");
			return (Criteria) this;
		}

		public Criteria andExamination_timeIsNotNull() {
			addCriterion("examination_time is not null");
			return (Criteria) this;
		}

		public Criteria andExamination_timeEqualTo(Date value) {
			addCriterionForJDBCDate("examination_time =", value, "examination_time");
			return (Criteria) this;
		}

		public Criteria andExamination_timeNotEqualTo(Date value) {
			addCriterionForJDBCDate("examination_time <>", value, "examination_time");
			return (Criteria) this;
		}

		public Criteria andExamination_timeGreaterThan(Date value) {
			addCriterionForJDBCDate("examination_time >", value, "examination_time");
			return (Criteria) this;
		}

		public Criteria andExamination_timeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("examination_time >=", value, "examination_time");
			return (Criteria) this;
		}

		public Criteria andExamination_timeLessThan(Date value) {
			addCriterionForJDBCDate("examination_time <", value, "examination_time");
			return (Criteria) this;
		}

		public Criteria andExamination_timeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("examination_time <=", value, "examination_time");
			return (Criteria) this;
		}

		public Criteria andExamination_timeIn(List<Date> values) {
			addCriterionForJDBCDate("examination_time in", values, "examination_time");
			return (Criteria) this;
		}

		public Criteria andExamination_timeNotIn(List<Date> values) {
			addCriterionForJDBCDate("examination_time not in", values, "examination_time");
			return (Criteria) this;
		}

		public Criteria andExamination_timeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("examination_time between", value1, value2, "examination_time");
			return (Criteria) this;
		}

		public Criteria andExamination_timeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("examination_time not between", value1, value2, "examination_time");
			return (Criteria) this;
		}

		public Criteria andStart_numberIsNull() {
			addCriterion("start_number is null");
			return (Criteria) this;
		}

		public Criteria andStart_numberIsNotNull() {
			addCriterion("start_number is not null");
			return (Criteria) this;
		}

		public Criteria andStart_numberEqualTo(Long value) {
			addCriterion("start_number =", value, "start_number");
			return (Criteria) this;
		}

		public Criteria andStart_numberNotEqualTo(Long value) {
			addCriterion("start_number <>", value, "start_number");
			return (Criteria) this;
		}

		public Criteria andStart_numberGreaterThan(Long value) {
			addCriterion("start_number >", value, "start_number");
			return (Criteria) this;
		}

		public Criteria andStart_numberGreaterThanOrEqualTo(Long value) {
			addCriterion("start_number >=", value, "start_number");
			return (Criteria) this;
		}

		public Criteria andStart_numberLessThan(Long value) {
			addCriterion("start_number <", value, "start_number");
			return (Criteria) this;
		}

		public Criteria andStart_numberLessThanOrEqualTo(Long value) {
			addCriterion("start_number <=", value, "start_number");
			return (Criteria) this;
		}

		public Criteria andStart_numberIn(List<Long> values) {
			addCriterion("start_number in", values, "start_number");
			return (Criteria) this;
		}

		public Criteria andStart_numberNotIn(List<Long> values) {
			addCriterion("start_number not in", values, "start_number");
			return (Criteria) this;
		}

		public Criteria andStart_numberBetween(Long value1, Long value2) {
			addCriterion("start_number between", value1, value2, "start_number");
			return (Criteria) this;
		}

		public Criteria andStart_numberNotBetween(Long value1, Long value2) {
			addCriterion("start_number not between", value1, value2, "start_number");
			return (Criteria) this;
		}

		public Criteria andTerminate_numberIsNull() {
			addCriterion("terminate_number is null");
			return (Criteria) this;
		}

		public Criteria andTerminate_numberIsNotNull() {
			addCriterion("terminate_number is not null");
			return (Criteria) this;
		}

		public Criteria andTerminate_numberEqualTo(Long value) {
			addCriterion("terminate_number =", value, "terminate_number");
			return (Criteria) this;
		}

		public Criteria andTerminate_numberNotEqualTo(Long value) {
			addCriterion("terminate_number <>", value, "terminate_number");
			return (Criteria) this;
		}

		public Criteria andTerminate_numberGreaterThan(Long value) {
			addCriterion("terminate_number >", value, "terminate_number");
			return (Criteria) this;
		}

		public Criteria andTerminate_numberGreaterThanOrEqualTo(Long value) {
			addCriterion("terminate_number >=", value, "terminate_number");
			return (Criteria) this;
		}

		public Criteria andTerminate_numberLessThan(Long value) {
			addCriterion("terminate_number <", value, "terminate_number");
			return (Criteria) this;
		}

		public Criteria andTerminate_numberLessThanOrEqualTo(Long value) {
			addCriterion("terminate_number <=", value, "terminate_number");
			return (Criteria) this;
		}

		public Criteria andTerminate_numberIn(List<Long> values) {
			addCriterion("terminate_number in", values, "terminate_number");
			return (Criteria) this;
		}

		public Criteria andTerminate_numberNotIn(List<Long> values) {
			addCriterion("terminate_number not in", values, "terminate_number");
			return (Criteria) this;
		}

		public Criteria andTerminate_numberBetween(Long value1, Long value2) {
			addCriterion("terminate_number between", value1, value2, "terminate_number");
			return (Criteria) this;
		}

		public Criteria andTerminate_numberNotBetween(Long value1, Long value2) {
			addCriterion("terminate_number not between", value1, value2, "terminate_number");
			return (Criteria) this;
		}

		public Criteria andMemoIsNull() {
			addCriterion("memo is null");
			return (Criteria) this;
		}

		public Criteria andMemoIsNotNull() {
			addCriterion("memo is not null");
			return (Criteria) this;
		}

		public Criteria andMemoEqualTo(String value) {
			addCriterion("memo =", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotEqualTo(String value) {
			addCriterion("memo <>", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoGreaterThan(String value) {
			addCriterion("memo >", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoGreaterThanOrEqualTo(String value) {
			addCriterion("memo >=", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoLessThan(String value) {
			addCriterion("memo <", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoLessThanOrEqualTo(String value) {
			addCriterion("memo <=", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoLike(String value) {
			addCriterion("memo like", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotLike(String value) {
			addCriterion("memo not like", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoIn(List<String> values) {
			addCriterion("memo in", values, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotIn(List<String> values) {
			addCriterion("memo not in", values, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoBetween(String value1, String value2) {
			addCriterion("memo between", value1, value2, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotBetween(String value1, String value2) {
			addCriterion("memo not between", value1, value2, "memo");
			return (Criteria) this;
		}

		public Criteria andCopies_numberIsNull() {
			addCriterion("copies_number is null");
			return (Criteria) this;
		}

		public Criteria andCopies_numberIsNotNull() {
			addCriterion("copies_number is not null");
			return (Criteria) this;
		}

		public Criteria andCopies_numberEqualTo(Integer value) {
			addCriterion("copies_number =", value, "copies_number");
			return (Criteria) this;
		}

		public Criteria andCopies_numberNotEqualTo(Integer value) {
			addCriterion("copies_number <>", value, "copies_number");
			return (Criteria) this;
		}

		public Criteria andCopies_numberGreaterThan(Integer value) {
			addCriterion("copies_number >", value, "copies_number");
			return (Criteria) this;
		}

		public Criteria andCopies_numberGreaterThanOrEqualTo(Integer value) {
			addCriterion("copies_number >=", value, "copies_number");
			return (Criteria) this;
		}

		public Criteria andCopies_numberLessThan(Integer value) {
			addCriterion("copies_number <", value, "copies_number");
			return (Criteria) this;
		}

		public Criteria andCopies_numberLessThanOrEqualTo(Integer value) {
			addCriterion("copies_number <=", value, "copies_number");
			return (Criteria) this;
		}

		public Criteria andCopies_numberIn(List<Integer> values) {
			addCriterion("copies_number in", values, "copies_number");
			return (Criteria) this;
		}

		public Criteria andCopies_numberNotIn(List<Integer> values) {
			addCriterion("copies_number not in", values, "copies_number");
			return (Criteria) this;
		}

		public Criteria andCopies_numberBetween(Integer value1, Integer value2) {
			addCriterion("copies_number between", value1, value2, "copies_number");
			return (Criteria) this;
		}

		public Criteria andCopies_numberNotBetween(Integer value1, Integer value2) {
			addCriterion("copies_number not between", value1, value2, "copies_number");
			return (Criteria) this;
		}

		public Criteria andDelete_statusIsNull() {
			addCriterion("delete_status is null");
			return (Criteria) this;
		}

		public Criteria andDelete_statusIsNotNull() {
			addCriterion("delete_status is not null");
			return (Criteria) this;
		}

		public Criteria andDelete_statusEqualTo(Integer value) {
			addCriterion("delete_status =", value, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusNotEqualTo(Integer value) {
			addCriterion("delete_status <>", value, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusGreaterThan(Integer value) {
			addCriterion("delete_status >", value, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusGreaterThanOrEqualTo(Integer value) {
			addCriterion("delete_status >=", value, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusLessThan(Integer value) {
			addCriterion("delete_status <", value, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusLessThanOrEqualTo(Integer value) {
			addCriterion("delete_status <=", value, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusIn(List<Integer> values) {
			addCriterion("delete_status in", values, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusNotIn(List<Integer> values) {
			addCriterion("delete_status not in", values, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusBetween(Integer value1, Integer value2) {
			addCriterion("delete_status between", value1, value2, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusNotBetween(Integer value1, Integer value2) {
			addCriterion("delete_status not between", value1, value2, "delete_status");
			return (Criteria) this;
		}

		public Criteria andCreate_dateIsNull() {
			addCriterion("create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreate_dateIsNotNull() {
			addCriterion("create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreate_dateEqualTo(Date value) {
			addCriterionForJDBCDate("create_date =", value, "create_date");
			return (Criteria) this;
		}

		public Criteria andCreate_dateNotEqualTo(Date value) {
			addCriterionForJDBCDate("create_date <>", value, "create_date");
			return (Criteria) this;
		}

		public Criteria andCreate_dateGreaterThan(Date value) {
			addCriterionForJDBCDate("create_date >", value, "create_date");
			return (Criteria) this;
		}

		public Criteria andCreate_dateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("create_date >=", value, "create_date");
			return (Criteria) this;
		}

		public Criteria andCreate_dateLessThan(Date value) {
			addCriterionForJDBCDate("create_date <", value, "create_date");
			return (Criteria) this;
		}

		public Criteria andCreate_dateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("create_date <=", value, "create_date");
			return (Criteria) this;
		}

		public Criteria andCreate_dateIn(List<Date> values) {
			addCriterionForJDBCDate("create_date in", values, "create_date");
			return (Criteria) this;
		}

		public Criteria andCreate_dateNotIn(List<Date> values) {
			addCriterionForJDBCDate("create_date not in", values, "create_date");
			return (Criteria) this;
		}

		public Criteria andCreate_dateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("create_date between", value1, value2, "create_date");
			return (Criteria) this;
		}

		public Criteria andCreate_dateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("create_date not between", value1, value2, "create_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateIsNull() {
			addCriterion("update_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateIsNotNull() {
			addCriterion("update_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateEqualTo(Date value) {
			addCriterionForJDBCDate("update_date =", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateNotEqualTo(Date value) {
			addCriterionForJDBCDate("update_date <>", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateGreaterThan(Date value) {
			addCriterionForJDBCDate("update_date >", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("update_date >=", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateLessThan(Date value) {
			addCriterionForJDBCDate("update_date <", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("update_date <=", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateIn(List<Date> values) {
			addCriterionForJDBCDate("update_date in", values, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateNotIn(List<Date> values) {
			addCriterionForJDBCDate("update_date not in", values, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("update_date between", value1, value2, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("update_date not between", value1, value2, "update_date");
			return (Criteria) this;
		}

		public Criteria andHoldIsNull() {
			addCriterion("hold is null");
			return (Criteria) this;
		}

		public Criteria andHoldIsNotNull() {
			addCriterion("hold is not null");
			return (Criteria) this;
		}

		public Criteria andHoldEqualTo(String value) {
			addCriterion("hold =", value, "hold");
			return (Criteria) this;
		}

		public Criteria andHoldNotEqualTo(String value) {
			addCriterion("hold <>", value, "hold");
			return (Criteria) this;
		}

		public Criteria andHoldGreaterThan(String value) {
			addCriterion("hold >", value, "hold");
			return (Criteria) this;
		}

		public Criteria andHoldGreaterThanOrEqualTo(String value) {
			addCriterion("hold >=", value, "hold");
			return (Criteria) this;
		}

		public Criteria andHoldLessThan(String value) {
			addCriterion("hold <", value, "hold");
			return (Criteria) this;
		}

		public Criteria andHoldLessThanOrEqualTo(String value) {
			addCriterion("hold <=", value, "hold");
			return (Criteria) this;
		}

		public Criteria andHoldLike(String value) {
			addCriterion("hold like", value, "hold");
			return (Criteria) this;
		}

		public Criteria andHoldNotLike(String value) {
			addCriterion("hold not like", value, "hold");
			return (Criteria) this;
		}

		public Criteria andHoldIn(List<String> values) {
			addCriterion("hold in", values, "hold");
			return (Criteria) this;
		}

		public Criteria andHoldNotIn(List<String> values) {
			addCriterion("hold not in", values, "hold");
			return (Criteria) this;
		}

		public Criteria andHoldBetween(String value1, String value2) {
			addCriterion("hold between", value1, value2, "hold");
			return (Criteria) this;
		}

		public Criteria andHoldNotBetween(String value1, String value2) {
			addCriterion("hold not between", value1, value2, "hold");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_bill_management_inspection_mingxi
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bill_management_inspection_mingxi
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 28 09:55:54 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}