package base.bill.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
/**
 * 票据信息维护
 * @author wangp
 * @time 2018-08-08
 */
public class TBillInfoMaintainExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public TBillInfoMaintainExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andBill_info_maintain_idIsNull() {
			addCriterion("bill_info_maintain_id is null");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idIsNotNull() {
			addCriterion("bill_info_maintain_id is not null");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idEqualTo(Integer value) {
			addCriterion("bill_info_maintain_id =", value, "bill_info_maintain_id");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idNotEqualTo(Integer value) {
			addCriterion("bill_info_maintain_id <>", value, "bill_info_maintain_id");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idGreaterThan(Integer value) {
			addCriterion("bill_info_maintain_id >", value, "bill_info_maintain_id");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("bill_info_maintain_id >=", value, "bill_info_maintain_id");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idLessThan(Integer value) {
			addCriterion("bill_info_maintain_id <", value, "bill_info_maintain_id");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idLessThanOrEqualTo(Integer value) {
			addCriterion("bill_info_maintain_id <=", value, "bill_info_maintain_id");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idIn(List<Integer> values) {
			addCriterion("bill_info_maintain_id in", values, "bill_info_maintain_id");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idNotIn(List<Integer> values) {
			addCriterion("bill_info_maintain_id not in", values, "bill_info_maintain_id");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idBetween(Integer value1, Integer value2) {
			addCriterion("bill_info_maintain_id between", value1, value2, "bill_info_maintain_id");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idNotBetween(Integer value1, Integer value2) {
			addCriterion("bill_info_maintain_id not between", value1, value2, "bill_info_maintain_id");
			return (Criteria) this;
		}

		public Criteria andBill_codeIsNull() {
			addCriterion("bill_code is null");
			return (Criteria) this;
		}

		public Criteria andBill_codeIsNotNull() {
			addCriterion("bill_code is not null");
			return (Criteria) this;
		}

		public Criteria andBill_codeEqualTo(String value) {
			addCriterion("bill_code =", value, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeNotEqualTo(String value) {
			addCriterion("bill_code <>", value, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeGreaterThan(String value) {
			addCriterion("bill_code >", value, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeGreaterThanOrEqualTo(String value) {
			addCriterion("bill_code >=", value, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeLessThan(String value) {
			addCriterion("bill_code <", value, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeLessThanOrEqualTo(String value) {
			addCriterion("bill_code <=", value, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeLike(String value) {
			addCriterion("bill_code like", value, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeNotLike(String value) {
			addCriterion("bill_code not like", value, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeIn(List<String> values) {
			addCriterion("bill_code in", values, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeNotIn(List<String> values) {
			addCriterion("bill_code not in", values, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeBetween(String value1, String value2) {
			addCriterion("bill_code between", value1, value2, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_codeNotBetween(String value1, String value2) {
			addCriterion("bill_code not between", value1, value2, "bill_code");
			return (Criteria) this;
		}

		public Criteria andBill_nameIsNull() {
			addCriterion("bill_name is null");
			return (Criteria) this;
		}

		public Criteria andBill_nameIsNotNull() {
			addCriterion("bill_name is not null");
			return (Criteria) this;
		}

		public Criteria andBill_nameEqualTo(String value) {
			addCriterion("bill_name =", value, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameNotEqualTo(String value) {
			addCriterion("bill_name <>", value, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameGreaterThan(String value) {
			addCriterion("bill_name >", value, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameGreaterThanOrEqualTo(String value) {
			addCriterion("bill_name >=", value, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameLessThan(String value) {
			addCriterion("bill_name <", value, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameLessThanOrEqualTo(String value) {
			addCriterion("bill_name <=", value, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameLike(String value) {
			addCriterion("bill_name like", value, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameNotLike(String value) {
			addCriterion("bill_name not like", value, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameIn(List<String> values) {
			addCriterion("bill_name in", values, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameNotIn(List<String> values) {
			addCriterion("bill_name not in", values, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameBetween(String value1, String value2) {
			addCriterion("bill_name between", value1, value2, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_nameNotBetween(String value1, String value2) {
			addCriterion("bill_name not between", value1, value2, "bill_name");
			return (Criteria) this;
		}

		public Criteria andBill_lengthIsNull() {
			addCriterion("bill_length is null");
			return (Criteria) this;
		}

		public Criteria andBill_lengthIsNotNull() {
			addCriterion("bill_length is not null");
			return (Criteria) this;
		}

		public Criteria andBill_lengthEqualTo(Integer value) {
			addCriterion("bill_length =", value, "bill_length");
			return (Criteria) this;
		}

		public Criteria andBill_lengthNotEqualTo(Integer value) {
			addCriterion("bill_length <>", value, "bill_length");
			return (Criteria) this;
		}

		public Criteria andBill_lengthGreaterThan(Integer value) {
			addCriterion("bill_length >", value, "bill_length");
			return (Criteria) this;
		}

		public Criteria andBill_lengthGreaterThanOrEqualTo(Integer value) {
			addCriterion("bill_length >=", value, "bill_length");
			return (Criteria) this;
		}

		public Criteria andBill_lengthLessThan(Integer value) {
			addCriterion("bill_length <", value, "bill_length");
			return (Criteria) this;
		}

		public Criteria andBill_lengthLessThanOrEqualTo(Integer value) {
			addCriterion("bill_length <=", value, "bill_length");
			return (Criteria) this;
		}

		public Criteria andBill_lengthIn(List<Integer> values) {
			addCriterion("bill_length in", values, "bill_length");
			return (Criteria) this;
		}

		public Criteria andBill_lengthNotIn(List<Integer> values) {
			addCriterion("bill_length not in", values, "bill_length");
			return (Criteria) this;
		}

		public Criteria andBill_lengthBetween(Integer value1, Integer value2) {
			addCriterion("bill_length between", value1, value2, "bill_length");
			return (Criteria) this;
		}

		public Criteria andBill_lengthNotBetween(Integer value1, Integer value2) {
			addCriterion("bill_length not between", value1, value2, "bill_length");
			return (Criteria) this;
		}

		public Criteria andStarttimeIsNull() {
			addCriterion("starttime is null");
			return (Criteria) this;
		}

		public Criteria andStarttimeIsNotNull() {
			addCriterion("starttime is not null");
			return (Criteria) this;
		}

		public Criteria andStarttimeEqualTo(Date value) {
			addCriterion("starttime =", value, "starttime");
			return (Criteria) this;
		}

		public Criteria andStarttimeNotEqualTo(Date value) {
			addCriterion("starttime <>", value, "starttime");
			return (Criteria) this;
		}

		public Criteria andStarttimeGreaterThan(Date value) {
			addCriterion("starttime >", value, "starttime");
			return (Criteria) this;
		}

		public Criteria andStarttimeGreaterThanOrEqualTo(Date value) {
			addCriterion("starttime >=", value, "starttime");
			return (Criteria) this;
		}

		public Criteria andStarttimeLessThan(Date value) {
			addCriterion("starttime <", value, "starttime");
			return (Criteria) this;
		}

		public Criteria andStarttimeLessThanOrEqualTo(Date value) {
			addCriterion("starttime <=", value, "starttime");
			return (Criteria) this;
		}

		public Criteria andStarttimeIn(List<Date> values) {
			addCriterion("starttime in", values, "starttime");
			return (Criteria) this;
		}

		public Criteria andStarttimeNotIn(List<Date> values) {
			addCriterion("starttime not in", values, "starttime");
			return (Criteria) this;
		}

		public Criteria andStarttimeBetween(Date value1, Date value2) {
			addCriterion("starttime between", value1, value2, "starttime");
			return (Criteria) this;
		}

		public Criteria andStarttimeNotBetween(Date value1, Date value2) {
			addCriterion("starttime not between", value1, value2, "starttime");
			return (Criteria) this;
		}

		public Criteria andEndtimeIsNull() {
			addCriterion("endtime is null");
			return (Criteria) this;
		}

		public Criteria andEndtimeIsNotNull() {
			addCriterion("endtime is not null");
			return (Criteria) this;
		}

		public Criteria andEndtimeEqualTo(Date value) {
			addCriterion("endtime =", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeNotEqualTo(Date value) {
			addCriterion("endtime <>", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeGreaterThan(Date value) {
			addCriterion("endtime >", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("endtime >=", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeLessThan(Date value) {
			addCriterion("endtime <", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeLessThanOrEqualTo(Date value) {
			addCriterion("endtime <=", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeIn(List<Date> values) {
			addCriterion("endtime in", values, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeNotIn(List<Date> values) {
			addCriterion("endtime not in", values, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeBetween(Date value1, Date value2) {
			addCriterion("endtime between", value1, value2, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeNotBetween(Date value1, Date value2) {
			addCriterion("endtime not between", value1, value2, "endtime");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andIs_useIsNull() {
			addCriterion("is_use is null");
			return (Criteria) this;
		}

		public Criteria andIs_useIsNotNull() {
			addCriterion("is_use is not null");
			return (Criteria) this;
		}

		public Criteria andIs_useEqualTo(Integer value) {
			addCriterion("is_use =", value, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useNotEqualTo(Integer value) {
			addCriterion("is_use <>", value, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useGreaterThan(Integer value) {
			addCriterion("is_use >", value, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_use >=", value, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useLessThan(Integer value) {
			addCriterion("is_use <", value, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useLessThanOrEqualTo(Integer value) {
			addCriterion("is_use <=", value, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useIn(List<Integer> values) {
			addCriterion("is_use in", values, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useNotIn(List<Integer> values) {
			addCriterion("is_use not in", values, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useBetween(Integer value1, Integer value2) {
			addCriterion("is_use between", value1, value2, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useNotBetween(Integer value1, Integer value2) {
			addCriterion("is_use not between", value1, value2, "is_use");
			return (Criteria) this;
		}

		public Criteria andDelete_statusIsNull() {
			addCriterion("delete_status is null");
			return (Criteria) this;
		}

		public Criteria andDelete_statusIsNotNull() {
			addCriterion("delete_status is not null");
			return (Criteria) this;
		}

		public Criteria andDelete_statusEqualTo(Integer value) {
			addCriterion("delete_status =", value, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusNotEqualTo(Integer value) {
			addCriterion("delete_status <>", value, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusGreaterThan(Integer value) {
			addCriterion("delete_status >", value, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusGreaterThanOrEqualTo(Integer value) {
			addCriterion("delete_status >=", value, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusLessThan(Integer value) {
			addCriterion("delete_status <", value, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusLessThanOrEqualTo(Integer value) {
			addCriterion("delete_status <=", value, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusIn(List<Integer> values) {
			addCriterion("delete_status in", values, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusNotIn(List<Integer> values) {
			addCriterion("delete_status not in", values, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusBetween(Integer value1, Integer value2) {
			addCriterion("delete_status between", value1, value2, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusNotBetween(Integer value1, Integer value2) {
			addCriterion("delete_status not between", value1, value2, "delete_status");
			return (Criteria) this;
		}

		public Criteria andBill_type_idIsNull() {
			addCriterion("bill_type_id is null");
			return (Criteria) this;
		}

		public Criteria andBill_type_idIsNotNull() {
			addCriterion("bill_type_id is not null");
			return (Criteria) this;
		}

		public Criteria andBill_type_idEqualTo(Integer value) {
			addCriterion("bill_type_id =", value, "bill_type_id");
			return (Criteria) this;
		}

		public Criteria andBill_type_idNotEqualTo(Integer value) {
			addCriterion("bill_type_id <>", value, "bill_type_id");
			return (Criteria) this;
		}

		public Criteria andBill_type_idGreaterThan(Integer value) {
			addCriterion("bill_type_id >", value, "bill_type_id");
			return (Criteria) this;
		}

		public Criteria andBill_type_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("bill_type_id >=", value, "bill_type_id");
			return (Criteria) this;
		}

		public Criteria andBill_type_idLessThan(Integer value) {
			addCriterion("bill_type_id <", value, "bill_type_id");
			return (Criteria) this;
		}

		public Criteria andBill_type_idLessThanOrEqualTo(Integer value) {
			addCriterion("bill_type_id <=", value, "bill_type_id");
			return (Criteria) this;
		}

		public Criteria andBill_type_idIn(List<Integer> values) {
			addCriterion("bill_type_id in", values, "bill_type_id");
			return (Criteria) this;
		}

		public Criteria andBill_type_idNotIn(List<Integer> values) {
			addCriterion("bill_type_id not in", values, "bill_type_id");
			return (Criteria) this;
		}

		public Criteria andBill_type_idBetween(Integer value1, Integer value2) {
			addCriterion("bill_type_id between", value1, value2, "bill_type_id");
			return (Criteria) this;
		}

		public Criteria andBill_type_idNotBetween(Integer value1, Integer value2) {
			addCriterion("bill_type_id not between", value1, value2, "bill_type_id");
			return (Criteria) this;
		}

		public Criteria andBill_sample_urlIsNull() {
			addCriterion("bill_sample_url is null");
			return (Criteria) this;
		}

		public Criteria andBill_sample_urlIsNotNull() {
			addCriterion("bill_sample_url is not null");
			return (Criteria) this;
		}

		public Criteria andBill_sample_urlEqualTo(String value) {
			addCriterion("bill_sample_url =", value, "bill_sample_url");
			return (Criteria) this;
		}

		public Criteria andBill_sample_urlNotEqualTo(String value) {
			addCriterion("bill_sample_url <>", value, "bill_sample_url");
			return (Criteria) this;
		}

		public Criteria andBill_sample_urlGreaterThan(String value) {
			addCriterion("bill_sample_url >", value, "bill_sample_url");
			return (Criteria) this;
		}

		public Criteria andBill_sample_urlGreaterThanOrEqualTo(String value) {
			addCriterion("bill_sample_url >=", value, "bill_sample_url");
			return (Criteria) this;
		}

		public Criteria andBill_sample_urlLessThan(String value) {
			addCriterion("bill_sample_url <", value, "bill_sample_url");
			return (Criteria) this;
		}

		public Criteria andBill_sample_urlLessThanOrEqualTo(String value) {
			addCriterion("bill_sample_url <=", value, "bill_sample_url");
			return (Criteria) this;
		}

		public Criteria andBill_sample_urlLike(String value) {
			addCriterion("bill_sample_url like", value, "bill_sample_url");
			return (Criteria) this;
		}

		public Criteria andBill_sample_urlNotLike(String value) {
			addCriterion("bill_sample_url not like", value, "bill_sample_url");
			return (Criteria) this;
		}

		public Criteria andBill_sample_urlIn(List<String> values) {
			addCriterion("bill_sample_url in", values, "bill_sample_url");
			return (Criteria) this;
		}

		public Criteria andBill_sample_urlNotIn(List<String> values) {
			addCriterion("bill_sample_url not in", values, "bill_sample_url");
			return (Criteria) this;
		}

		public Criteria andBill_sample_urlBetween(String value1, String value2) {
			addCriterion("bill_sample_url between", value1, value2, "bill_sample_url");
			return (Criteria) this;
		}

		public Criteria andBill_sample_urlNotBetween(String value1, String value2) {
			addCriterion("bill_sample_url not between", value1, value2, "bill_sample_url");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_bill_info_maintain
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bill_info_maintain
     *
     * @mbg.generated do_not_delete_during_merge Wed Aug 08 10:13:11 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}