package base.bill.entity;

import java.util.Date;

public class TBillPplicationDestruction {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_pplication_destruction.id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_pplication_destruction.applicant_number
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String applicant_number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_pplication_destruction.applicant_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Date applicant_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_pplication_destruction.company_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String company_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_pplication_destruction.company_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String company_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_pplication_destruction.operator
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String operator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_pplication_destruction.memo
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String memo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_pplication_destruction.report_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer report_status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_pplication_destruction.financial_examine_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer financial_examine_status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_pplication_destruction.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer delete_status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_pplication_destruction.create_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Date create_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_pplication_destruction.update_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Date update_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_pplication_destruction.hold
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String hold;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_pplication_destruction.id
	 * @return  the value of t_bill_pplication_destruction.id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_pplication_destruction.id
	 * @param id  the value for t_bill_pplication_destruction.id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_pplication_destruction.applicant_number
	 * @return  the value of t_bill_pplication_destruction.applicant_number
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getApplicant_number() {
		return applicant_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_pplication_destruction.applicant_number
	 * @param applicant_number  the value for t_bill_pplication_destruction.applicant_number
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setApplicant_number(String applicant_number) {
		this.applicant_number = applicant_number == null ? null : applicant_number.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_pplication_destruction.applicant_time
	 * @return  the value of t_bill_pplication_destruction.applicant_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getApplicant_time() {
		return applicant_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_pplication_destruction.applicant_time
	 * @param applicant_time  the value for t_bill_pplication_destruction.applicant_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setApplicant_time(Date applicant_time) {
		this.applicant_time = applicant_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_pplication_destruction.company_code
	 * @return  the value of t_bill_pplication_destruction.company_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getCompany_code() {
		return company_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_pplication_destruction.company_code
	 * @param company_code  the value for t_bill_pplication_destruction.company_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCompany_code(String company_code) {
		this.company_code = company_code == null ? null : company_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_pplication_destruction.company_name
	 * @return  the value of t_bill_pplication_destruction.company_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getCompany_name() {
		return company_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_pplication_destruction.company_name
	 * @param company_name  the value for t_bill_pplication_destruction.company_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCompany_name(String company_name) {
		this.company_name = company_name == null ? null : company_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_pplication_destruction.operator
	 * @return  the value of t_bill_pplication_destruction.operator
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_pplication_destruction.operator
	 * @param operator  the value for t_bill_pplication_destruction.operator
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setOperator(String operator) {
		this.operator = operator == null ? null : operator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_pplication_destruction.memo
	 * @return  the value of t_bill_pplication_destruction.memo
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_pplication_destruction.memo
	 * @param memo  the value for t_bill_pplication_destruction.memo
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setMemo(String memo) {
		this.memo = memo == null ? null : memo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_pplication_destruction.report_status
	 * @return  the value of t_bill_pplication_destruction.report_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getReport_status() {
		return report_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_pplication_destruction.report_status
	 * @param report_status  the value for t_bill_pplication_destruction.report_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setReport_status(Integer report_status) {
		this.report_status = report_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_pplication_destruction.financial_examine_status
	 * @return  the value of t_bill_pplication_destruction.financial_examine_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getFinancial_examine_status() {
		return financial_examine_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_pplication_destruction.financial_examine_status
	 * @param financial_examine_status  the value for t_bill_pplication_destruction.financial_examine_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setFinancial_examine_status(Integer financial_examine_status) {
		this.financial_examine_status = financial_examine_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_pplication_destruction.delete_status
	 * @return  the value of t_bill_pplication_destruction.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getDelete_status() {
		return delete_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_pplication_destruction.delete_status
	 * @param delete_status  the value for t_bill_pplication_destruction.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setDelete_status(Integer delete_status) {
		this.delete_status = delete_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_pplication_destruction.create_date
	 * @return  the value of t_bill_pplication_destruction.create_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getCreate_date() {
		return create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_pplication_destruction.create_date
	 * @param create_date  the value for t_bill_pplication_destruction.create_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCreate_date(Date create_date) {
		this.create_date = create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_pplication_destruction.update_date
	 * @return  the value of t_bill_pplication_destruction.update_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getUpdate_date() {
		return update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_pplication_destruction.update_date
	 * @param update_date  the value for t_bill_pplication_destruction.update_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setUpdate_date(Date update_date) {
		this.update_date = update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_pplication_destruction.hold
	 * @return  the value of t_bill_pplication_destruction.hold
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getHold() {
		return hold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_pplication_destruction.hold
	 * @param hold  the value for t_bill_pplication_destruction.hold
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setHold(String hold) {
		this.hold = hold == null ? null : hold.trim();
	}
}