package base.bill.entity;

import java.util.Date;

import org.jeecgframework.poi.excel.annotation.Excel;
/**
 * 票据缴验申请 明细表
 * @author wangp
 * @time 2018-08-08
 */
public class TBillManagementInspectionMingxi {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection_mingxi.mingxi_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "主键mingxi_id", mergeVertical = true, isImportField = "id")
	private Integer mingxi_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection_mingxi.id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "外键Id", mergeVertical = true, isImportField = "id")
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection_mingxi.bill_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "票据编码", mergeVertical = true, isImportField = "bill_code")
	private String bill_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection_mingxi.bill_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "票据名称", mergeVertical = true, isImportField = "bill_name")
	private String bill_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection_mingxi.bill_prefix
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "票据前缀 0没有 1 有", mergeVertical = true, isImportField = "bill_prefix")
	private Integer bill_prefix;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection_mingxi.examination_type
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "缴验类型0 遗失 1. 作废", mergeVertical = true, isImportField = "examination_type")
	private Integer examination_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection_mingxi.examination_reasons
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "缴验原因", mergeVertical = true, isImportField = "examination_reasons")
	private String examination_reasons;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection_mingxi.examination_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "缴验时间", mergeVertical = true, isImportField = "examination_time")
	private Date examination_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection_mingxi.start_number
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "起始号码", mergeVertical = true, isImportField = "start_number")
	private Long start_number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection_mingxi.terminate_number
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "终止号码", mergeVertical = true, isImportField = "terminate_number")
	private Long terminate_number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection_mingxi.memo
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "备注", mergeVertical = true, isImportField = "memo")
	private String memo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection_mingxi.copies_number
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "份数", mergeVertical = true, isImportField = "copies_number")
	private Integer copies_number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection_mingxi.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "删除状态", mergeVertical = true, isImportField = "delete_status")
	private Integer delete_status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection_mingxi.create_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "创建日期", mergeVertical = true, isImportField = "create_date")
	private Date create_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection_mingxi.update_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "更新日期", mergeVertical = true, isImportField = "update_date")
	private Date update_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_management_inspection_mingxi.hold
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "备用字段", mergeVertical = true, isImportField = "hold")
	private String hold;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection_mingxi.mingxi_id
	 * @return  the value of t_bill_management_inspection_mingxi.mingxi_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getMingxi_id() {
		return mingxi_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection_mingxi.mingxi_id
	 * @param mingxi_id  the value for t_bill_management_inspection_mingxi.mingxi_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setMingxi_id(Integer mingxi_id) {
		this.mingxi_id = mingxi_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection_mingxi.id
	 * @return  the value of t_bill_management_inspection_mingxi.id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection_mingxi.id
	 * @param id  the value for t_bill_management_inspection_mingxi.id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection_mingxi.bill_code
	 * @return  the value of t_bill_management_inspection_mingxi.bill_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getBill_code() {
		return bill_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection_mingxi.bill_code
	 * @param bill_code  the value for t_bill_management_inspection_mingxi.bill_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setBill_code(String bill_code) {
		this.bill_code = bill_code == null ? null : bill_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection_mingxi.bill_name
	 * @return  the value of t_bill_management_inspection_mingxi.bill_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getBill_name() {
		return bill_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection_mingxi.bill_name
	 * @param bill_name  the value for t_bill_management_inspection_mingxi.bill_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setBill_name(String bill_name) {
		this.bill_name = bill_name == null ? null : bill_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection_mingxi.bill_prefix
	 * @return  the value of t_bill_management_inspection_mingxi.bill_prefix
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getBill_prefix() {
		return bill_prefix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection_mingxi.bill_prefix
	 * @param bill_prefix  the value for t_bill_management_inspection_mingxi.bill_prefix
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setBill_prefix(Integer bill_prefix) {
		this.bill_prefix = bill_prefix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection_mingxi.examination_type
	 * @return  the value of t_bill_management_inspection_mingxi.examination_type
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getExamination_type() {
		return examination_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection_mingxi.examination_type
	 * @param examination_type  the value for t_bill_management_inspection_mingxi.examination_type
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setExamination_type(Integer examination_type) {
		this.examination_type = examination_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection_mingxi.examination_reasons
	 * @return  the value of t_bill_management_inspection_mingxi.examination_reasons
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getExamination_reasons() {
		return examination_reasons;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection_mingxi.examination_reasons
	 * @param examination_reasons  the value for t_bill_management_inspection_mingxi.examination_reasons
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setExamination_reasons(String examination_reasons) {
		this.examination_reasons = examination_reasons == null ? null : examination_reasons.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection_mingxi.examination_time
	 * @return  the value of t_bill_management_inspection_mingxi.examination_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getExamination_time() {
		return examination_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection_mingxi.examination_time
	 * @param examination_time  the value for t_bill_management_inspection_mingxi.examination_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setExamination_time(Date examination_time) {
		this.examination_time = examination_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection_mingxi.start_number
	 * @return  the value of t_bill_management_inspection_mingxi.start_number
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Long getStart_number() {
		return start_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection_mingxi.start_number
	 * @param start_number  the value for t_bill_management_inspection_mingxi.start_number
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setStart_number(Long start_number) {
		this.start_number = start_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection_mingxi.terminate_number
	 * @return  the value of t_bill_management_inspection_mingxi.terminate_number
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Long getTerminate_number() {
		return terminate_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection_mingxi.terminate_number
	 * @param terminate_number  the value for t_bill_management_inspection_mingxi.terminate_number
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setTerminate_number(Long terminate_number) {
		this.terminate_number = terminate_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection_mingxi.memo
	 * @return  the value of t_bill_management_inspection_mingxi.memo
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection_mingxi.memo
	 * @param memo  the value for t_bill_management_inspection_mingxi.memo
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setMemo(String memo) {
		this.memo = memo == null ? null : memo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection_mingxi.copies_number
	 * @return  the value of t_bill_management_inspection_mingxi.copies_number
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getCopies_number() {
		return copies_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection_mingxi.copies_number
	 * @param copies_number  the value for t_bill_management_inspection_mingxi.copies_number
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCopies_number(Integer copies_number) {
		this.copies_number = copies_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection_mingxi.delete_status
	 * @return  the value of t_bill_management_inspection_mingxi.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getDelete_status() {
		return delete_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection_mingxi.delete_status
	 * @param delete_status  the value for t_bill_management_inspection_mingxi.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setDelete_status(Integer delete_status) {
		this.delete_status = delete_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection_mingxi.create_date
	 * @return  the value of t_bill_management_inspection_mingxi.create_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getCreate_date() {
		return create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection_mingxi.create_date
	 * @param create_date  the value for t_bill_management_inspection_mingxi.create_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCreate_date(Date create_date) {
		this.create_date = create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection_mingxi.update_date
	 * @return  the value of t_bill_management_inspection_mingxi.update_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getUpdate_date() {
		return update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection_mingxi.update_date
	 * @param update_date  the value for t_bill_management_inspection_mingxi.update_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setUpdate_date(Date update_date) {
		this.update_date = update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_management_inspection_mingxi.hold
	 * @return  the value of t_bill_management_inspection_mingxi.hold
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getHold() {
		return hold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_management_inspection_mingxi.hold
	 * @param hold  the value for t_bill_management_inspection_mingxi.hold
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setHold(String hold) {
		this.hold = hold == null ? null : hold.trim();
	}
}