package base.bill.entity;

import java.util.Date;

public class TContinbutors {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_continbutors.id
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_continbutors.t_full_contributors_name
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	private String t_full_contributors_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_continbutors.t_full_contributors_bank
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	private String t_full_contributors_bank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_continbutors.t_add_date
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	private Date t_add_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_continbutors.t_full_contributors_bank_number
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	private String t_full_contributors_bank_number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_continbutors.t_full_contributors_code
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	private String t_full_contributors_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_continbutors.delete_status
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	private Integer delete_status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_continbutors.t_create_date
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	private Date t_create_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_continbutors.t_update_date
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	private Date t_update_date;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_continbutors.id
	 * @return  the value of t_continbutors.id
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_continbutors.id
	 * @param id  the value for t_continbutors.id
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_continbutors.t_full_contributors_name
	 * @return  the value of t_continbutors.t_full_contributors_name
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	public String getT_full_contributors_name() {
		return t_full_contributors_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_continbutors.t_full_contributors_name
	 * @param t_full_contributors_name  the value for t_continbutors.t_full_contributors_name
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	public void setT_full_contributors_name(String t_full_contributors_name) {
		this.t_full_contributors_name = t_full_contributors_name == null ? null : t_full_contributors_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_continbutors.t_full_contributors_bank
	 * @return  the value of t_continbutors.t_full_contributors_bank
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	public String getT_full_contributors_bank() {
		return t_full_contributors_bank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_continbutors.t_full_contributors_bank
	 * @param t_full_contributors_bank  the value for t_continbutors.t_full_contributors_bank
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	public void setT_full_contributors_bank(String t_full_contributors_bank) {
		this.t_full_contributors_bank = t_full_contributors_bank == null ? null : t_full_contributors_bank.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_continbutors.t_add_date
	 * @return  the value of t_continbutors.t_add_date
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	public Date getT_add_date() {
		return t_add_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_continbutors.t_add_date
	 * @param t_add_date  the value for t_continbutors.t_add_date
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	public void setT_add_date(Date t_add_date) {
		this.t_add_date = t_add_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_continbutors.t_full_contributors_bank_number
	 * @return  the value of t_continbutors.t_full_contributors_bank_number
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	public String getT_full_contributors_bank_number() {
		return t_full_contributors_bank_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_continbutors.t_full_contributors_bank_number
	 * @param t_full_contributors_bank_number  the value for t_continbutors.t_full_contributors_bank_number
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	public void setT_full_contributors_bank_number(String t_full_contributors_bank_number) {
		this.t_full_contributors_bank_number = t_full_contributors_bank_number == null ? null
				: t_full_contributors_bank_number.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_continbutors.t_full_contributors_code
	 * @return  the value of t_continbutors.t_full_contributors_code
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	public String getT_full_contributors_code() {
		return t_full_contributors_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_continbutors.t_full_contributors_code
	 * @param t_full_contributors_code  the value for t_continbutors.t_full_contributors_code
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	public void setT_full_contributors_code(String t_full_contributors_code) {
		this.t_full_contributors_code = t_full_contributors_code == null ? null : t_full_contributors_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_continbutors.delete_status
	 * @return  the value of t_continbutors.delete_status
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	public Integer getDelete_status() {
		return delete_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_continbutors.delete_status
	 * @param delete_status  the value for t_continbutors.delete_status
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	public void setDelete_status(Integer delete_status) {
		this.delete_status = delete_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_continbutors.t_create_date
	 * @return  the value of t_continbutors.t_create_date
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	public Date getT_create_date() {
		return t_create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_continbutors.t_create_date
	 * @param t_create_date  the value for t_continbutors.t_create_date
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	public void setT_create_date(Date t_create_date) {
		this.t_create_date = t_create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_continbutors.t_update_date
	 * @return  the value of t_continbutors.t_update_date
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	public Date getT_update_date() {
		return t_update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_continbutors.t_update_date
	 * @param t_update_date  the value for t_continbutors.t_update_date
	 * @mbg.generated  Sat Aug 11 10:11:56 CST 2018
	 */
	public void setT_update_date(Date t_update_date) {
		this.t_update_date = t_update_date;
	}
}