package base.bill.entity;

import java.math.BigDecimal;
import java.util.Date;

import org.jeecgframework.poi.excel.annotation.Excel;
/**
 * 一般缴款信息服务（直接缴款服务和汇缴服务）
 * @author wangp
 * @time 2018-08-08
 */
public class TDemandNote {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.demand_note_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "主键ID", mergeVertical = true, isImportField = "demand_note_id")
	private Integer demand_note_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.adm_div_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "行政区划", mergeVertical = true, isImportField = "adm_div_code")
	private String adm_div_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.pay_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "缴款码", mergeVertical = true, isImportField = "pay_code")
	private String pay_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.bill_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "填制日期（开票日期）", mergeVertical = true, isImportField = "bill_date")
	private Date bill_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.chg_agen_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "执收单位编码", mergeVertical = true, isImportField = "chg_agen_code")
	private String chg_agen_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.chg_agen_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "执收单位名称", mergeVertical = true, isImportField = "chg_agen_name")
	private String chg_agen_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.payer_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "缴（付）款人账户全称", mergeVertical = true, isImportField = "payer_name")
	private String payer_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.payer_acc
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "缴（付）款人账号", mergeVertical = true, isImportField = "payer_acc")
	private String payer_acc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.payer_op_bk
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "缴（付）款人开户行", mergeVertical = true, isImportField = "payer_op_bk")
	private String payer_op_bk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.payer_op_bk_no
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "缴（付）款人开户行行号", mergeVertical = true, isImportField = "payer_op_bk_no")
	private String payer_op_bk_no;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.amt
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "缴款金额合计", mergeVertical = true, isImportField = "amt")
	private BigDecimal amt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.ori_amt
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "缴款书金额", mergeVertical = true, isImportField = "ori_amt")
	private BigDecimal ori_amt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.delay_amt
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "滞纳金", mergeVertical = true, isImportField = "delay_amt")
	private Long delay_amt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.pay_stats
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "缴款状态（0：未交款，1：已交款；2：填开（已开）；3：作废；4：退付；5：核销；）", mergeVertical = true, isImportField = "pay_stats")
	private String pay_stats;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.payment_method
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "缴款方式：现金、支票 默认显示现金", mergeVertical = true, isImportField = "payment_method")
	private String payment_method;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.rec_acct_type
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "收款人账户类型（见附录5）", mergeVertical = true, isImportField = "rec_acct_type")
	private String rec_acct_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.rec_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "收款人全称（当收款人账户类型为科目时，可为空）", mergeVertical = true, isImportField = "rec_name")
	private String rec_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.rec_acct
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "收款人账号（当收款人账户类型为科目时，可为空）", mergeVertical = true, isImportField = "rec_acct")
	private String rec_acct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.rec_op_bk
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "收款人开户行（当收款人账户类型为科目时，可为空）", mergeVertical = true, isImportField = "rec_op_bk")
	private String rec_op_bk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.rec_bank_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "收款人开户行银行编码", mergeVertical = true, isImportField = "rec_bank_code")
	private String rec_bank_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.rec_agent_bank_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "收款人开户行代理银行名称（如：中国银行）", mergeVertical = true, isImportField = "rec_agent_bank_name")
	private String rec_agent_bank_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.income_project_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "收入项目编码", mergeVertical = true, isImportField = "income_project_code")
	private String income_project_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.income_project_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "收入项目名称", mergeVertical = true, isImportField = "income_project_name")
	private String income_project_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.unit_collection
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "计收单位", mergeVertical = true, isImportField = "unit_collection")
	private String unit_collection;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.number
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "数量", mergeVertical = true, isImportField = "number")
	private String number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.charge_standard
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "收费标准", mergeVertical = true, isImportField = "charge_standard")
	private String charge_standard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.amount_money
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "金额", mergeVertical = true, isImportField = "amount_money")
	private BigDecimal amount_money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.total_amount_uppercase
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "合计大写金额", mergeVertical = true, isImportField = "total_amount_uppercase")
	private String total_amount_uppercase;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.total_amount_lowercase
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "合计小写金额", mergeVertical = true, isImportField = "total_amount_lowercase")
	private BigDecimal total_amount_lowercase;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.automatic_memory
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "是否自动记忆（复选框 记忆代表新增数据）", mergeVertical = true, isImportField = "automatic_memory")
	private String automatic_memory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.check_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "校验码", mergeVertical = true, isImportField = "check_code")
	private String check_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.pay_mode
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "收款渠道（见附录2）", mergeVertical = true, isImportField = "pay_mode")
	private String pay_mode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.is_inter_bank
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "是否跨行（0本行，1跨行）", mergeVertical = true, isImportField = "is_inter_bank")
	private String is_inter_bank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.bank_outlet
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "银行网点编码（POS刷卡和网上支付时填写商户号）", mergeVertical = true, isImportField = "bank_outlet")
	private String bank_outlet;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.tra_no_bus
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "确认交易流水号（缴款时交易流水号，要保证行内唯一）", mergeVertical = true, isImportField = "tra_no_bus")
	private String tra_no_bus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.operator
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "经办人", mergeVertical = true, isImportField = "operator")
	private String operator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.pay_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "摘要（全国统一项目识别码+项目名称+金额，信息以分隔符进行分割，如：全国统一项目识别码1|项目名称1|2.0#全国统一项目识别码2|项目名称2|3.0#，也可以为财政定义的其他格式）", mergeVertical = true, isImportField = "pay_info")
	private String pay_info;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.cfm_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "缴款日期", mergeVertical = true, isImportField = "cfm_date")
	private Date cfm_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.cfm_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "缴款时间", mergeVertical = true, isImportField = "cfm_time")
	private Date cfm_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.memo
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "备注", mergeVertical = true, isImportField = "memo")
	private String memo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.kindmoney_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "类款编码", mergeVertical = true, isImportField = "kindmoney_code")
	private String kindmoney_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.kindmoney_fullname
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "类款全称", mergeVertical = true, isImportField = "kindmoney_fullname")
	private String kindmoney_fullname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.bill_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "票据编码", mergeVertical = true, isImportField = "bill_code")
	private String bill_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.bill_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String bill_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.bill_no
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "票据号码", mergeVertical = true, isImportField = "bill_no")
	private String bill_no;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.application_refund_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "申请退款时间", mergeVertical = true, isImportField = "application_refund_date")
	private Date application_refund_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.audit_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "审核状态0待审核，1已通过，2未通过", mergeVertical = true, isImportField = "audit_status")
	private Integer audit_status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.audit_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "审核时间", mergeVertical = true, isImportField = "audit_date")
	private Date audit_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.not_pass_reason
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "未通过原因", mergeVertical = true, isImportField = "not_pass_reason")
	private String not_pass_reason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.financial_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "财政id", mergeVertical = true, isImportField = "financial_id")
	private Integer financial_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.create_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "创建时间", mergeVertical = true, isImportField = "create_date")
	private Date create_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.update_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "更新时间", mergeVertical = true, isImportField = "update_date")
	private Date update_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.source_payment_mode
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "缴款模式 来源 （0：直缴模式 1：大厅模式 委托业务 2. 集缴模式）", mergeVertical = true, isImportField = "source_payment_mode")
	private Integer source_payment_mode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.print_state
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "打印状态（1为打印 0为未打印）", mergeVertical = true, isImportField = "print_state")
	private Integer print_state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "删除状态", mergeVertical = true, isImportField = "delete_status")
	private Integer delete_status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.payment_state
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "缴款状态（1为已缴款 0为未缴款）", mergeVertical = true, isImportField = "payment_state")
	private Integer payment_state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.reconciliation_state
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "对账状态（1为已对账 0为未对账）", mergeVertical = true, isImportField = "reconciliation_state")
	private Integer reconciliation_state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.return_state
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "回执状态（1为已回执 0为未回执）", mergeVertical = true, isImportField = "return_state")
	private Integer return_state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.invalidated_state
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "作废状态（1为已作废 0为未作废）", mergeVertical = true, isImportField = "invalidated_state")
	private Integer invalidated_state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.record_state
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "补录状态（1为已补录 0为未补录）", mergeVertical = true, isImportField = "record_state")
	private Integer record_state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.summary_state
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer summary_state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_demand_note.hold2
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "预留字段", mergeVertical = true, isImportField = "hold2")
	private String hold2;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.demand_note_id
	 * @return  the value of t_demand_note.demand_note_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getDemand_note_id() {
		return demand_note_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.demand_note_id
	 * @param demand_note_id  the value for t_demand_note.demand_note_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setDemand_note_id(Integer demand_note_id) {
		this.demand_note_id = demand_note_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.adm_div_code
	 * @return  the value of t_demand_note.adm_div_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getAdm_div_code() {
		return adm_div_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.adm_div_code
	 * @param adm_div_code  the value for t_demand_note.adm_div_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setAdm_div_code(String adm_div_code) {
		this.adm_div_code = adm_div_code == null ? null : adm_div_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.id
	 * @return  the value of t_demand_note.id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.id
	 * @param id  the value for t_demand_note.id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.pay_code
	 * @return  the value of t_demand_note.pay_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getPay_code() {
		return pay_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.pay_code
	 * @param pay_code  the value for t_demand_note.pay_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setPay_code(String pay_code) {
		this.pay_code = pay_code == null ? null : pay_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.bill_date
	 * @return  the value of t_demand_note.bill_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getBill_date() {
		return bill_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.bill_date
	 * @param bill_date  the value for t_demand_note.bill_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setBill_date(Date bill_date) {
		this.bill_date = bill_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.chg_agen_code
	 * @return  the value of t_demand_note.chg_agen_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getChg_agen_code() {
		return chg_agen_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.chg_agen_code
	 * @param chg_agen_code  the value for t_demand_note.chg_agen_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setChg_agen_code(String chg_agen_code) {
		this.chg_agen_code = chg_agen_code == null ? null : chg_agen_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.chg_agen_name
	 * @return  the value of t_demand_note.chg_agen_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getChg_agen_name() {
		return chg_agen_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.chg_agen_name
	 * @param chg_agen_name  the value for t_demand_note.chg_agen_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setChg_agen_name(String chg_agen_name) {
		this.chg_agen_name = chg_agen_name == null ? null : chg_agen_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.payer_name
	 * @return  the value of t_demand_note.payer_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getPayer_name() {
		return payer_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.payer_name
	 * @param payer_name  the value for t_demand_note.payer_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setPayer_name(String payer_name) {
		this.payer_name = payer_name == null ? null : payer_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.payer_acc
	 * @return  the value of t_demand_note.payer_acc
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getPayer_acc() {
		return payer_acc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.payer_acc
	 * @param payer_acc  the value for t_demand_note.payer_acc
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setPayer_acc(String payer_acc) {
		this.payer_acc = payer_acc == null ? null : payer_acc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.payer_op_bk
	 * @return  the value of t_demand_note.payer_op_bk
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getPayer_op_bk() {
		return payer_op_bk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.payer_op_bk
	 * @param payer_op_bk  the value for t_demand_note.payer_op_bk
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setPayer_op_bk(String payer_op_bk) {
		this.payer_op_bk = payer_op_bk == null ? null : payer_op_bk.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.payer_op_bk_no
	 * @return  the value of t_demand_note.payer_op_bk_no
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getPayer_op_bk_no() {
		return payer_op_bk_no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.payer_op_bk_no
	 * @param payer_op_bk_no  the value for t_demand_note.payer_op_bk_no
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setPayer_op_bk_no(String payer_op_bk_no) {
		this.payer_op_bk_no = payer_op_bk_no == null ? null : payer_op_bk_no.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.amt
	 * @return  the value of t_demand_note.amt
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public BigDecimal getAmt() {
		return amt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.amt
	 * @param amt  the value for t_demand_note.amt
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setAmt(BigDecimal amt) {
		this.amt = amt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.ori_amt
	 * @return  the value of t_demand_note.ori_amt
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public BigDecimal getOri_amt() {
		return ori_amt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.ori_amt
	 * @param ori_amt  the value for t_demand_note.ori_amt
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setOri_amt(BigDecimal ori_amt) {
		this.ori_amt = ori_amt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.delay_amt
	 * @return  the value of t_demand_note.delay_amt
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Long getDelay_amt() {
		return delay_amt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.delay_amt
	 * @param delay_amt  the value for t_demand_note.delay_amt
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setDelay_amt(Long delay_amt) {
		this.delay_amt = delay_amt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.pay_stats
	 * @return  the value of t_demand_note.pay_stats
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getPay_stats() {
		return pay_stats;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.pay_stats
	 * @param pay_stats  the value for t_demand_note.pay_stats
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setPay_stats(String pay_stats) {
		this.pay_stats = pay_stats == null ? null : pay_stats.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.payment_method
	 * @return  the value of t_demand_note.payment_method
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getPayment_method() {
		return payment_method;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.payment_method
	 * @param payment_method  the value for t_demand_note.payment_method
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setPayment_method(String payment_method) {
		this.payment_method = payment_method == null ? null : payment_method.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.rec_acct_type
	 * @return  the value of t_demand_note.rec_acct_type
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getRec_acct_type() {
		return rec_acct_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.rec_acct_type
	 * @param rec_acct_type  the value for t_demand_note.rec_acct_type
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setRec_acct_type(String rec_acct_type) {
		this.rec_acct_type = rec_acct_type == null ? null : rec_acct_type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.rec_name
	 * @return  the value of t_demand_note.rec_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getRec_name() {
		return rec_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.rec_name
	 * @param rec_name  the value for t_demand_note.rec_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setRec_name(String rec_name) {
		this.rec_name = rec_name == null ? null : rec_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.rec_acct
	 * @return  the value of t_demand_note.rec_acct
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getRec_acct() {
		return rec_acct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.rec_acct
	 * @param rec_acct  the value for t_demand_note.rec_acct
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setRec_acct(String rec_acct) {
		this.rec_acct = rec_acct == null ? null : rec_acct.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.rec_op_bk
	 * @return  the value of t_demand_note.rec_op_bk
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getRec_op_bk() {
		return rec_op_bk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.rec_op_bk
	 * @param rec_op_bk  the value for t_demand_note.rec_op_bk
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setRec_op_bk(String rec_op_bk) {
		this.rec_op_bk = rec_op_bk == null ? null : rec_op_bk.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.rec_bank_code
	 * @return  the value of t_demand_note.rec_bank_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getRec_bank_code() {
		return rec_bank_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.rec_bank_code
	 * @param rec_bank_code  the value for t_demand_note.rec_bank_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setRec_bank_code(String rec_bank_code) {
		this.rec_bank_code = rec_bank_code == null ? null : rec_bank_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.rec_agent_bank_name
	 * @return  the value of t_demand_note.rec_agent_bank_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getRec_agent_bank_name() {
		return rec_agent_bank_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.rec_agent_bank_name
	 * @param rec_agent_bank_name  the value for t_demand_note.rec_agent_bank_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setRec_agent_bank_name(String rec_agent_bank_name) {
		this.rec_agent_bank_name = rec_agent_bank_name == null ? null : rec_agent_bank_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.income_project_code
	 * @return  the value of t_demand_note.income_project_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getIncome_project_code() {
		return income_project_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.income_project_code
	 * @param income_project_code  the value for t_demand_note.income_project_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setIncome_project_code(String income_project_code) {
		this.income_project_code = income_project_code == null ? null : income_project_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.income_project_name
	 * @return  the value of t_demand_note.income_project_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getIncome_project_name() {
		return income_project_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.income_project_name
	 * @param income_project_name  the value for t_demand_note.income_project_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setIncome_project_name(String income_project_name) {
		this.income_project_name = income_project_name == null ? null : income_project_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.unit_collection
	 * @return  the value of t_demand_note.unit_collection
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getUnit_collection() {
		return unit_collection;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.unit_collection
	 * @param unit_collection  the value for t_demand_note.unit_collection
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setUnit_collection(String unit_collection) {
		this.unit_collection = unit_collection == null ? null : unit_collection.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.number
	 * @return  the value of t_demand_note.number
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getNumber() {
		return number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.number
	 * @param number  the value for t_demand_note.number
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setNumber(String number) {
		this.number = number == null ? null : number.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.charge_standard
	 * @return  the value of t_demand_note.charge_standard
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getCharge_standard() {
		return charge_standard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.charge_standard
	 * @param charge_standard  the value for t_demand_note.charge_standard
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCharge_standard(String charge_standard) {
		this.charge_standard = charge_standard == null ? null : charge_standard.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.amount_money
	 * @return  the value of t_demand_note.amount_money
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public BigDecimal getAmount_money() {
		return amount_money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.amount_money
	 * @param amount_money  the value for t_demand_note.amount_money
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setAmount_money(BigDecimal amount_money) {
		this.amount_money = amount_money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.total_amount_uppercase
	 * @return  the value of t_demand_note.total_amount_uppercase
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getTotal_amount_uppercase() {
		return total_amount_uppercase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.total_amount_uppercase
	 * @param total_amount_uppercase  the value for t_demand_note.total_amount_uppercase
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setTotal_amount_uppercase(String total_amount_uppercase) {
		this.total_amount_uppercase = total_amount_uppercase == null ? null : total_amount_uppercase.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.total_amount_lowercase
	 * @return  the value of t_demand_note.total_amount_lowercase
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public BigDecimal getTotal_amount_lowercase() {
		return total_amount_lowercase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.total_amount_lowercase
	 * @param total_amount_lowercase  the value for t_demand_note.total_amount_lowercase
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setTotal_amount_lowercase(BigDecimal total_amount_lowercase) {
		this.total_amount_lowercase = total_amount_lowercase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.automatic_memory
	 * @return  the value of t_demand_note.automatic_memory
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getAutomatic_memory() {
		return automatic_memory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.automatic_memory
	 * @param automatic_memory  the value for t_demand_note.automatic_memory
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setAutomatic_memory(String automatic_memory) {
		this.automatic_memory = automatic_memory == null ? null : automatic_memory.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.check_code
	 * @return  the value of t_demand_note.check_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getCheck_code() {
		return check_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.check_code
	 * @param check_code  the value for t_demand_note.check_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCheck_code(String check_code) {
		this.check_code = check_code == null ? null : check_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.pay_mode
	 * @return  the value of t_demand_note.pay_mode
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getPay_mode() {
		return pay_mode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.pay_mode
	 * @param pay_mode  the value for t_demand_note.pay_mode
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setPay_mode(String pay_mode) {
		this.pay_mode = pay_mode == null ? null : pay_mode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.is_inter_bank
	 * @return  the value of t_demand_note.is_inter_bank
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getIs_inter_bank() {
		return is_inter_bank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.is_inter_bank
	 * @param is_inter_bank  the value for t_demand_note.is_inter_bank
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setIs_inter_bank(String is_inter_bank) {
		this.is_inter_bank = is_inter_bank == null ? null : is_inter_bank.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.bank_outlet
	 * @return  the value of t_demand_note.bank_outlet
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getBank_outlet() {
		return bank_outlet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.bank_outlet
	 * @param bank_outlet  the value for t_demand_note.bank_outlet
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setBank_outlet(String bank_outlet) {
		this.bank_outlet = bank_outlet == null ? null : bank_outlet.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.tra_no_bus
	 * @return  the value of t_demand_note.tra_no_bus
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getTra_no_bus() {
		return tra_no_bus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.tra_no_bus
	 * @param tra_no_bus  the value for t_demand_note.tra_no_bus
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setTra_no_bus(String tra_no_bus) {
		this.tra_no_bus = tra_no_bus == null ? null : tra_no_bus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.operator
	 * @return  the value of t_demand_note.operator
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.operator
	 * @param operator  the value for t_demand_note.operator
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setOperator(String operator) {
		this.operator = operator == null ? null : operator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.pay_info
	 * @return  the value of t_demand_note.pay_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getPay_info() {
		return pay_info;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.pay_info
	 * @param pay_info  the value for t_demand_note.pay_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setPay_info(String pay_info) {
		this.pay_info = pay_info == null ? null : pay_info.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.cfm_date
	 * @return  the value of t_demand_note.cfm_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getCfm_date() {
		return cfm_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.cfm_date
	 * @param cfm_date  the value for t_demand_note.cfm_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCfm_date(Date cfm_date) {
		this.cfm_date = cfm_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.cfm_time
	 * @return  the value of t_demand_note.cfm_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getCfm_time() {
		return cfm_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.cfm_time
	 * @param cfm_time  the value for t_demand_note.cfm_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCfm_time(Date cfm_time) {
		this.cfm_time = cfm_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.memo
	 * @return  the value of t_demand_note.memo
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.memo
	 * @param memo  the value for t_demand_note.memo
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setMemo(String memo) {
		this.memo = memo == null ? null : memo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.kindmoney_code
	 * @return  the value of t_demand_note.kindmoney_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getKindmoney_code() {
		return kindmoney_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.kindmoney_code
	 * @param kindmoney_code  the value for t_demand_note.kindmoney_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setKindmoney_code(String kindmoney_code) {
		this.kindmoney_code = kindmoney_code == null ? null : kindmoney_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.kindmoney_fullname
	 * @return  the value of t_demand_note.kindmoney_fullname
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getKindmoney_fullname() {
		return kindmoney_fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.kindmoney_fullname
	 * @param kindmoney_fullname  the value for t_demand_note.kindmoney_fullname
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setKindmoney_fullname(String kindmoney_fullname) {
		this.kindmoney_fullname = kindmoney_fullname == null ? null : kindmoney_fullname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.bill_code
	 * @return  the value of t_demand_note.bill_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getBill_code() {
		return bill_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.bill_code
	 * @param bill_code  the value for t_demand_note.bill_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setBill_code(String bill_code) {
		this.bill_code = bill_code == null ? null : bill_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.bill_name
	 * @return  the value of t_demand_note.bill_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getBill_name() {
		return bill_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.bill_name
	 * @param bill_name  the value for t_demand_note.bill_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setBill_name(String bill_name) {
		this.bill_name = bill_name == null ? null : bill_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.bill_no
	 * @return  the value of t_demand_note.bill_no
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getBill_no() {
		return bill_no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.bill_no
	 * @param bill_no  the value for t_demand_note.bill_no
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setBill_no(String bill_no) {
		this.bill_no = bill_no == null ? null : bill_no.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.application_refund_date
	 * @return  the value of t_demand_note.application_refund_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getApplication_refund_date() {
		return application_refund_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.application_refund_date
	 * @param application_refund_date  the value for t_demand_note.application_refund_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setApplication_refund_date(Date application_refund_date) {
		this.application_refund_date = application_refund_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.audit_status
	 * @return  the value of t_demand_note.audit_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getAudit_status() {
		return audit_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.audit_status
	 * @param audit_status  the value for t_demand_note.audit_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setAudit_status(Integer audit_status) {
		this.audit_status = audit_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.audit_date
	 * @return  the value of t_demand_note.audit_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getAudit_date() {
		return audit_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.audit_date
	 * @param audit_date  the value for t_demand_note.audit_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setAudit_date(Date audit_date) {
		this.audit_date = audit_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.not_pass_reason
	 * @return  the value of t_demand_note.not_pass_reason
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getNot_pass_reason() {
		return not_pass_reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.not_pass_reason
	 * @param not_pass_reason  the value for t_demand_note.not_pass_reason
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setNot_pass_reason(String not_pass_reason) {
		this.not_pass_reason = not_pass_reason == null ? null : not_pass_reason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.financial_id
	 * @return  the value of t_demand_note.financial_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getFinancial_id() {
		return financial_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.financial_id
	 * @param financial_id  the value for t_demand_note.financial_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setFinancial_id(Integer financial_id) {
		this.financial_id = financial_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.create_date
	 * @return  the value of t_demand_note.create_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getCreate_date() {
		return create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.create_date
	 * @param create_date  the value for t_demand_note.create_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCreate_date(Date create_date) {
		this.create_date = create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.update_date
	 * @return  the value of t_demand_note.update_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getUpdate_date() {
		return update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.update_date
	 * @param update_date  the value for t_demand_note.update_date
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setUpdate_date(Date update_date) {
		this.update_date = update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.source_payment_mode
	 * @return  the value of t_demand_note.source_payment_mode
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getSource_payment_mode() {
		return source_payment_mode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.source_payment_mode
	 * @param source_payment_mode  the value for t_demand_note.source_payment_mode
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setSource_payment_mode(Integer source_payment_mode) {
		this.source_payment_mode = source_payment_mode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.print_state
	 * @return  the value of t_demand_note.print_state
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getPrint_state() {
		return print_state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.print_state
	 * @param print_state  the value for t_demand_note.print_state
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setPrint_state(Integer print_state) {
		this.print_state = print_state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.delete_status
	 * @return  the value of t_demand_note.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getDelete_status() {
		return delete_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.delete_status
	 * @param delete_status  the value for t_demand_note.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setDelete_status(Integer delete_status) {
		this.delete_status = delete_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.payment_state
	 * @return  the value of t_demand_note.payment_state
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getPayment_state() {
		return payment_state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.payment_state
	 * @param payment_state  the value for t_demand_note.payment_state
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setPayment_state(Integer payment_state) {
		this.payment_state = payment_state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.reconciliation_state
	 * @return  the value of t_demand_note.reconciliation_state
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getReconciliation_state() {
		return reconciliation_state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.reconciliation_state
	 * @param reconciliation_state  the value for t_demand_note.reconciliation_state
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setReconciliation_state(Integer reconciliation_state) {
		this.reconciliation_state = reconciliation_state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.return_state
	 * @return  the value of t_demand_note.return_state
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getReturn_state() {
		return return_state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.return_state
	 * @param return_state  the value for t_demand_note.return_state
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setReturn_state(Integer return_state) {
		this.return_state = return_state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.invalidated_state
	 * @return  the value of t_demand_note.invalidated_state
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getInvalidated_state() {
		return invalidated_state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.invalidated_state
	 * @param invalidated_state  the value for t_demand_note.invalidated_state
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setInvalidated_state(Integer invalidated_state) {
		this.invalidated_state = invalidated_state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.record_state
	 * @return  the value of t_demand_note.record_state
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getRecord_state() {
		return record_state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.record_state
	 * @param record_state  the value for t_demand_note.record_state
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setRecord_state(Integer record_state) {
		this.record_state = record_state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.summary_state
	 * @return  the value of t_demand_note.summary_state
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getSummary_state() {
		return summary_state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.summary_state
	 * @param summary_state  the value for t_demand_note.summary_state
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setSummary_state(Integer summary_state) {
		this.summary_state = summary_state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_demand_note.hold2
	 * @return  the value of t_demand_note.hold2
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getHold2() {
		return hold2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_demand_note.hold2
	 * @param hold2  the value for t_demand_note.hold2
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setHold2(String hold2) {
		this.hold2 = hold2 == null ? null : hold2.trim();
	}

	void state() {
	}

	void state(String print) {
	}

	
}