package base.bill.entity;

import java.util.Date;

import org.jeecgframework.poi.excel.annotation.Excel;
/**
 * 暂保押申请信息管理
 * @author Administrator
 *
 */
public class TEmporaryGuaranteeApplication {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emporary_guarantee_application.id
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emporary_guarantee_application.application_temporary_number
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    @Excel(name = "暂保押申请编号", mergeVertical = true, isImportField = "application_temporary_number")
    private String application_temporary_number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emporary_guarantee_application.bill_number
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    @Excel(name = "缴款书编号", mergeVertical = true, isImportField = "bill_number")
    private String bill_number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emporary_guarantee_application.application_date
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    @Excel(name = "申请日期", mergeVertical = true, isImportField = "application_date")
    private Date application_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emporary_guarantee_application.unit_code
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    @Excel(name = "单位编码", mergeVertical = true, isImportField = "unit_code")
    private String unit_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emporary_guarantee_application.unit_name
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    @Excel(name = "单位名称", mergeVertical = true, isImportField = "unit_name")
    private String unit_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emporary_guarantee_application.reporte_state
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    @Excel(name = "上报状态（1已上报 0未上报）", mergeVertical = true, isImportField = "reporte_state")
    private Integer reporte_state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emporary_guarantee_application.audit_state
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    @Excel(name = "审核状态(1已审核成功 2审核失败 0未审核 3 审核中)", mergeVertical = true, isImportField = "audit_state")
    private Integer audit_state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emporary_guarantee_application.delete_state
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    @Excel(name = "删除状态", mergeVertical = true, isImportField = "delete_state")
    private Integer delete_state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emporary_guarantee_application.create_date
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    @Excel(name = "创建日期", mergeVertical = true, isImportField = "create_date")
    private Date create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emporary_guarantee_application.update_date
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    @Excel(name = "更新日期", mergeVertical = true, isImportField = "update_date")
    private Date update_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emporary_guarantee_application.hold
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    @Excel(name = "备用字段", mergeVertical = true, isImportField = "hold")
    private String hold;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emporary_guarantee_application.id
     *
     * @return the value of t_emporary_guarantee_application.id
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emporary_guarantee_application.id
     *
     * @param id the value for t_emporary_guarantee_application.id
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emporary_guarantee_application.application_temporary_number
     *
     * @return the value of t_emporary_guarantee_application.application_temporary_number
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public String getApplication_temporary_number() {
        return application_temporary_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emporary_guarantee_application.application_temporary_number
     *
     * @param application_temporary_number the value for t_emporary_guarantee_application.application_temporary_number
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public void setApplication_temporary_number(String application_temporary_number) {
        this.application_temporary_number = application_temporary_number == null ? null : application_temporary_number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emporary_guarantee_application.bill_number
     *
     * @return the value of t_emporary_guarantee_application.bill_number
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public String getBill_number() {
        return bill_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emporary_guarantee_application.bill_number
     *
     * @param bill_number the value for t_emporary_guarantee_application.bill_number
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public void setBill_number(String bill_number) {
        this.bill_number = bill_number == null ? null : bill_number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emporary_guarantee_application.application_date
     *
     * @return the value of t_emporary_guarantee_application.application_date
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public Date getApplication_date() {
        return application_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emporary_guarantee_application.application_date
     *
     * @param application_date the value for t_emporary_guarantee_application.application_date
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public void setApplication_date(Date application_date) {
        this.application_date = application_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emporary_guarantee_application.unit_code
     *
     * @return the value of t_emporary_guarantee_application.unit_code
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public String getUnit_code() {
        return unit_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emporary_guarantee_application.unit_code
     *
     * @param unit_code the value for t_emporary_guarantee_application.unit_code
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public void setUnit_code(String unit_code) {
        this.unit_code = unit_code == null ? null : unit_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emporary_guarantee_application.unit_name
     *
     * @return the value of t_emporary_guarantee_application.unit_name
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public String getUnit_name() {
        return unit_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emporary_guarantee_application.unit_name
     *
     * @param unit_name the value for t_emporary_guarantee_application.unit_name
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public void setUnit_name(String unit_name) {
        this.unit_name = unit_name == null ? null : unit_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emporary_guarantee_application.reporte_state
     *
     * @return the value of t_emporary_guarantee_application.reporte_state
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public Integer getReporte_state() {
        return reporte_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emporary_guarantee_application.reporte_state
     *
     * @param reporte_state the value for t_emporary_guarantee_application.reporte_state
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public void setReporte_state(Integer reporte_state) {
        this.reporte_state = reporte_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emporary_guarantee_application.audit_state
     *
     * @return the value of t_emporary_guarantee_application.audit_state
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public Integer getAudit_state() {
        return audit_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emporary_guarantee_application.audit_state
     *
     * @param audit_state the value for t_emporary_guarantee_application.audit_state
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public void setAudit_state(Integer audit_state) {
        this.audit_state = audit_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emporary_guarantee_application.delete_state
     *
     * @return the value of t_emporary_guarantee_application.delete_state
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public Integer getDelete_state() {
        return delete_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emporary_guarantee_application.delete_state
     *
     * @param delete_state the value for t_emporary_guarantee_application.delete_state
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public void setDelete_state(Integer delete_state) {
        this.delete_state = delete_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emporary_guarantee_application.create_date
     *
     * @return the value of t_emporary_guarantee_application.create_date
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emporary_guarantee_application.create_date
     *
     * @param create_date the value for t_emporary_guarantee_application.create_date
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emporary_guarantee_application.update_date
     *
     * @return the value of t_emporary_guarantee_application.update_date
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public Date getUpdate_date() {
        return update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emporary_guarantee_application.update_date
     *
     * @param update_date the value for t_emporary_guarantee_application.update_date
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public void setUpdate_date(Date update_date) {
        this.update_date = update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emporary_guarantee_application.hold
     *
     * @return the value of t_emporary_guarantee_application.hold
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public String getHold() {
        return hold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emporary_guarantee_application.hold
     *
     * @param hold the value for t_emporary_guarantee_application.hold
     *
     * @mbg.generated Wed Sep 05 10:25:24 CST 2018
     */
    public void setHold(String hold) {
        this.hold = hold == null ? null : hold.trim();
    }
}