package base.bill.entity;

import java.util.Date;

public class TFinancial {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_financial.financial_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer financial_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_financial.financial_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String financial_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_financial.financial_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String financial_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_financial.link_man
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String link_man;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_financial.phone
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_financial.mail
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String mail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_financial.pay_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private String pay_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_financial.parent_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer parent_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_financial.create_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Date create_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_financial.modify_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Date modify_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_financial.is_use_dept_bill
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer is_use_dept_bill;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_financial.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer delete_status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_financial.financial_id
	 * @return  the value of t_financial.financial_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getFinancial_id() {
		return financial_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_financial.financial_id
	 * @param financial_id  the value for t_financial.financial_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setFinancial_id(Integer financial_id) {
		this.financial_id = financial_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_financial.financial_code
	 * @return  the value of t_financial.financial_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getFinancial_code() {
		return financial_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_financial.financial_code
	 * @param financial_code  the value for t_financial.financial_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setFinancial_code(String financial_code) {
		this.financial_code = financial_code == null ? null : financial_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_financial.financial_name
	 * @return  the value of t_financial.financial_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getFinancial_name() {
		return financial_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_financial.financial_name
	 * @param financial_name  the value for t_financial.financial_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setFinancial_name(String financial_name) {
		this.financial_name = financial_name == null ? null : financial_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_financial.link_man
	 * @return  the value of t_financial.link_man
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getLink_man() {
		return link_man;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_financial.link_man
	 * @param link_man  the value for t_financial.link_man
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setLink_man(String link_man) {
		this.link_man = link_man == null ? null : link_man.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_financial.phone
	 * @return  the value of t_financial.phone
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_financial.phone
	 * @param phone  the value for t_financial.phone
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_financial.mail
	 * @return  the value of t_financial.mail
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getMail() {
		return mail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_financial.mail
	 * @param mail  the value for t_financial.mail
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setMail(String mail) {
		this.mail = mail == null ? null : mail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_financial.pay_name
	 * @return  the value of t_financial.pay_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getPay_name() {
		return pay_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_financial.pay_name
	 * @param pay_name  the value for t_financial.pay_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setPay_name(String pay_name) {
		this.pay_name = pay_name == null ? null : pay_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_financial.parent_id
	 * @return  the value of t_financial.parent_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getParent_id() {
		return parent_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_financial.parent_id
	 * @param parent_id  the value for t_financial.parent_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setParent_id(Integer parent_id) {
		this.parent_id = parent_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_financial.create_time
	 * @return  the value of t_financial.create_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getCreate_time() {
		return create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_financial.create_time
	 * @param create_time  the value for t_financial.create_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_financial.modify_time
	 * @return  the value of t_financial.modify_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getModify_time() {
		return modify_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_financial.modify_time
	 * @param modify_time  the value for t_financial.modify_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setModify_time(Date modify_time) {
		this.modify_time = modify_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_financial.is_use_dept_bill
	 * @return  the value of t_financial.is_use_dept_bill
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getIs_use_dept_bill() {
		return is_use_dept_bill;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_financial.is_use_dept_bill
	 * @param is_use_dept_bill  the value for t_financial.is_use_dept_bill
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setIs_use_dept_bill(Integer is_use_dept_bill) {
		this.is_use_dept_bill = is_use_dept_bill;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_financial.delete_status
	 * @return  the value of t_financial.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getDelete_status() {
		return delete_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_financial.delete_status
	 * @param delete_status  the value for t_financial.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setDelete_status(Integer delete_status) {
		this.delete_status = delete_status;
	}
}