package base.bill.entity;

public class TImposingUnitNproject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_imposing_unit_nproject.imposing_unit_nproject_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer imposing_unit_nproject_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_imposing_unit_nproject.imposing_unit_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer imposing_unit_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_imposing_unit_nproject.notax_project_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer notax_project_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_imposing_unit_nproject.capital_property
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer capital_property;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_imposing_unit_nproject.is_use
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer is_use;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_imposing_unit_nproject.imposing_unit_nproject_id
	 * @return  the value of t_imposing_unit_nproject.imposing_unit_nproject_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getImposing_unit_nproject_id() {
		return imposing_unit_nproject_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_imposing_unit_nproject.imposing_unit_nproject_id
	 * @param imposing_unit_nproject_id  the value for t_imposing_unit_nproject.imposing_unit_nproject_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setImposing_unit_nproject_id(Integer imposing_unit_nproject_id) {
		this.imposing_unit_nproject_id = imposing_unit_nproject_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_imposing_unit_nproject.imposing_unit_id
	 * @return  the value of t_imposing_unit_nproject.imposing_unit_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getImposing_unit_id() {
		return imposing_unit_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_imposing_unit_nproject.imposing_unit_id
	 * @param imposing_unit_id  the value for t_imposing_unit_nproject.imposing_unit_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setImposing_unit_id(Integer imposing_unit_id) {
		this.imposing_unit_id = imposing_unit_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_imposing_unit_nproject.notax_project_id
	 * @return  the value of t_imposing_unit_nproject.notax_project_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getNotax_project_id() {
		return notax_project_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_imposing_unit_nproject.notax_project_id
	 * @param notax_project_id  the value for t_imposing_unit_nproject.notax_project_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setNotax_project_id(Integer notax_project_id) {
		this.notax_project_id = notax_project_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_imposing_unit_nproject.capital_property
	 * @return  the value of t_imposing_unit_nproject.capital_property
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getCapital_property() {
		return capital_property;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_imposing_unit_nproject.capital_property
	 * @param capital_property  the value for t_imposing_unit_nproject.capital_property
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCapital_property(Integer capital_property) {
		this.capital_property = capital_property;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_imposing_unit_nproject.is_use
	 * @return  the value of t_imposing_unit_nproject.is_use
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getIs_use() {
		return is_use;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_imposing_unit_nproject.is_use
	 * @param is_use  the value for t_imposing_unit_nproject.is_use
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setIs_use(Integer is_use) {
		this.is_use = is_use;
	}
}