package base.bill.entity;

import java.util.ArrayList;
import java.util.List;

public class TImposingUnitNprojectExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_imposing_unit_nproject
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_imposing_unit_nproject
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_imposing_unit_nproject
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit_nproject
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public TImposingUnitNprojectExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit_nproject
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit_nproject
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit_nproject
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit_nproject
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit_nproject
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit_nproject
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit_nproject
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit_nproject
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit_nproject
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_imposing_unit_nproject
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_imposing_unit_nproject
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andImposing_unit_nproject_idIsNull() {
			addCriterion("imposing_unit_nproject_id is null");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_nproject_idIsNotNull() {
			addCriterion("imposing_unit_nproject_id is not null");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_nproject_idEqualTo(Integer value) {
			addCriterion("imposing_unit_nproject_id =", value, "imposing_unit_nproject_id");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_nproject_idNotEqualTo(Integer value) {
			addCriterion("imposing_unit_nproject_id <>", value, "imposing_unit_nproject_id");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_nproject_idGreaterThan(Integer value) {
			addCriterion("imposing_unit_nproject_id >", value, "imposing_unit_nproject_id");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_nproject_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("imposing_unit_nproject_id >=", value, "imposing_unit_nproject_id");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_nproject_idLessThan(Integer value) {
			addCriterion("imposing_unit_nproject_id <", value, "imposing_unit_nproject_id");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_nproject_idLessThanOrEqualTo(Integer value) {
			addCriterion("imposing_unit_nproject_id <=", value, "imposing_unit_nproject_id");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_nproject_idIn(List<Integer> values) {
			addCriterion("imposing_unit_nproject_id in", values, "imposing_unit_nproject_id");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_nproject_idNotIn(List<Integer> values) {
			addCriterion("imposing_unit_nproject_id not in", values, "imposing_unit_nproject_id");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_nproject_idBetween(Integer value1, Integer value2) {
			addCriterion("imposing_unit_nproject_id between", value1, value2, "imposing_unit_nproject_id");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_nproject_idNotBetween(Integer value1, Integer value2) {
			addCriterion("imposing_unit_nproject_id not between", value1, value2, "imposing_unit_nproject_id");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_idIsNull() {
			addCriterion("imposing_unit_id is null");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_idIsNotNull() {
			addCriterion("imposing_unit_id is not null");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_idEqualTo(Integer value) {
			addCriterion("imposing_unit_id =", value, "imposing_unit_id");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_idNotEqualTo(Integer value) {
			addCriterion("imposing_unit_id <>", value, "imposing_unit_id");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_idGreaterThan(Integer value) {
			addCriterion("imposing_unit_id >", value, "imposing_unit_id");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("imposing_unit_id >=", value, "imposing_unit_id");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_idLessThan(Integer value) {
			addCriterion("imposing_unit_id <", value, "imposing_unit_id");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_idLessThanOrEqualTo(Integer value) {
			addCriterion("imposing_unit_id <=", value, "imposing_unit_id");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_idIn(List<Integer> values) {
			addCriterion("imposing_unit_id in", values, "imposing_unit_id");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_idNotIn(List<Integer> values) {
			addCriterion("imposing_unit_id not in", values, "imposing_unit_id");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_idBetween(Integer value1, Integer value2) {
			addCriterion("imposing_unit_id between", value1, value2, "imposing_unit_id");
			return (Criteria) this;
		}

		public Criteria andImposing_unit_idNotBetween(Integer value1, Integer value2) {
			addCriterion("imposing_unit_id not between", value1, value2, "imposing_unit_id");
			return (Criteria) this;
		}

		public Criteria andNotax_project_idIsNull() {
			addCriterion("notax_project_id is null");
			return (Criteria) this;
		}

		public Criteria andNotax_project_idIsNotNull() {
			addCriterion("notax_project_id is not null");
			return (Criteria) this;
		}

		public Criteria andNotax_project_idEqualTo(Integer value) {
			addCriterion("notax_project_id =", value, "notax_project_id");
			return (Criteria) this;
		}

		public Criteria andNotax_project_idNotEqualTo(Integer value) {
			addCriterion("notax_project_id <>", value, "notax_project_id");
			return (Criteria) this;
		}

		public Criteria andNotax_project_idGreaterThan(Integer value) {
			addCriterion("notax_project_id >", value, "notax_project_id");
			return (Criteria) this;
		}

		public Criteria andNotax_project_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("notax_project_id >=", value, "notax_project_id");
			return (Criteria) this;
		}

		public Criteria andNotax_project_idLessThan(Integer value) {
			addCriterion("notax_project_id <", value, "notax_project_id");
			return (Criteria) this;
		}

		public Criteria andNotax_project_idLessThanOrEqualTo(Integer value) {
			addCriterion("notax_project_id <=", value, "notax_project_id");
			return (Criteria) this;
		}

		public Criteria andNotax_project_idIn(List<Integer> values) {
			addCriterion("notax_project_id in", values, "notax_project_id");
			return (Criteria) this;
		}

		public Criteria andNotax_project_idNotIn(List<Integer> values) {
			addCriterion("notax_project_id not in", values, "notax_project_id");
			return (Criteria) this;
		}

		public Criteria andNotax_project_idBetween(Integer value1, Integer value2) {
			addCriterion("notax_project_id between", value1, value2, "notax_project_id");
			return (Criteria) this;
		}

		public Criteria andNotax_project_idNotBetween(Integer value1, Integer value2) {
			addCriterion("notax_project_id not between", value1, value2, "notax_project_id");
			return (Criteria) this;
		}

		public Criteria andCapital_propertyIsNull() {
			addCriterion("capital_property is null");
			return (Criteria) this;
		}

		public Criteria andCapital_propertyIsNotNull() {
			addCriterion("capital_property is not null");
			return (Criteria) this;
		}

		public Criteria andCapital_propertyEqualTo(Integer value) {
			addCriterion("capital_property =", value, "capital_property");
			return (Criteria) this;
		}

		public Criteria andCapital_propertyNotEqualTo(Integer value) {
			addCriterion("capital_property <>", value, "capital_property");
			return (Criteria) this;
		}

		public Criteria andCapital_propertyGreaterThan(Integer value) {
			addCriterion("capital_property >", value, "capital_property");
			return (Criteria) this;
		}

		public Criteria andCapital_propertyGreaterThanOrEqualTo(Integer value) {
			addCriterion("capital_property >=", value, "capital_property");
			return (Criteria) this;
		}

		public Criteria andCapital_propertyLessThan(Integer value) {
			addCriterion("capital_property <", value, "capital_property");
			return (Criteria) this;
		}

		public Criteria andCapital_propertyLessThanOrEqualTo(Integer value) {
			addCriterion("capital_property <=", value, "capital_property");
			return (Criteria) this;
		}

		public Criteria andCapital_propertyIn(List<Integer> values) {
			addCriterion("capital_property in", values, "capital_property");
			return (Criteria) this;
		}

		public Criteria andCapital_propertyNotIn(List<Integer> values) {
			addCriterion("capital_property not in", values, "capital_property");
			return (Criteria) this;
		}

		public Criteria andCapital_propertyBetween(Integer value1, Integer value2) {
			addCriterion("capital_property between", value1, value2, "capital_property");
			return (Criteria) this;
		}

		public Criteria andCapital_propertyNotBetween(Integer value1, Integer value2) {
			addCriterion("capital_property not between", value1, value2, "capital_property");
			return (Criteria) this;
		}

		public Criteria andIs_useIsNull() {
			addCriterion("is_use is null");
			return (Criteria) this;
		}

		public Criteria andIs_useIsNotNull() {
			addCriterion("is_use is not null");
			return (Criteria) this;
		}

		public Criteria andIs_useEqualTo(Integer value) {
			addCriterion("is_use =", value, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useNotEqualTo(Integer value) {
			addCriterion("is_use <>", value, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useGreaterThan(Integer value) {
			addCriterion("is_use >", value, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_use >=", value, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useLessThan(Integer value) {
			addCriterion("is_use <", value, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useLessThanOrEqualTo(Integer value) {
			addCriterion("is_use <=", value, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useIn(List<Integer> values) {
			addCriterion("is_use in", values, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useNotIn(List<Integer> values) {
			addCriterion("is_use not in", values, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useBetween(Integer value1, Integer value2) {
			addCriterion("is_use between", value1, value2, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useNotBetween(Integer value1, Integer value2) {
			addCriterion("is_use not between", value1, value2, "is_use");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_imposing_unit_nproject
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_imposing_unit_nproject
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 09 15:32:09 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}