package base.bill.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TLevyFallExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_levy_fall
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_levy_fall
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_levy_fall
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levy_fall
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public TLevyFallExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levy_fall
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levy_fall
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levy_fall
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levy_fall
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levy_fall
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levy_fall
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levy_fall
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levy_fall
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levy_fall
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levy_fall
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_levy_fall
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andLevyfall_idIsNull() {
			addCriterion("levyfall_id is null");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idIsNotNull() {
			addCriterion("levyfall_id is not null");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idEqualTo(Integer value) {
			addCriterion("levyfall_id =", value, "levyfall_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idNotEqualTo(Integer value) {
			addCriterion("levyfall_id <>", value, "levyfall_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idGreaterThan(Integer value) {
			addCriterion("levyfall_id >", value, "levyfall_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("levyfall_id >=", value, "levyfall_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idLessThan(Integer value) {
			addCriterion("levyfall_id <", value, "levyfall_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idLessThanOrEqualTo(Integer value) {
			addCriterion("levyfall_id <=", value, "levyfall_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idIn(List<Integer> values) {
			addCriterion("levyfall_id in", values, "levyfall_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idNotIn(List<Integer> values) {
			addCriterion("levyfall_id not in", values, "levyfall_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idBetween(Integer value1, Integer value2) {
			addCriterion("levyfall_id between", value1, value2, "levyfall_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idNotBetween(Integer value1, Integer value2) {
			addCriterion("levyfall_id not between", value1, value2, "levyfall_id");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andSpecial_managerIsNull() {
			addCriterion("special_manager is null");
			return (Criteria) this;
		}

		public Criteria andSpecial_managerIsNotNull() {
			addCriterion("special_manager is not null");
			return (Criteria) this;
		}

		public Criteria andSpecial_managerEqualTo(String value) {
			addCriterion("special_manager =", value, "special_manager");
			return (Criteria) this;
		}

		public Criteria andSpecial_managerNotEqualTo(String value) {
			addCriterion("special_manager <>", value, "special_manager");
			return (Criteria) this;
		}

		public Criteria andSpecial_managerGreaterThan(String value) {
			addCriterion("special_manager >", value, "special_manager");
			return (Criteria) this;
		}

		public Criteria andSpecial_managerGreaterThanOrEqualTo(String value) {
			addCriterion("special_manager >=", value, "special_manager");
			return (Criteria) this;
		}

		public Criteria andSpecial_managerLessThan(String value) {
			addCriterion("special_manager <", value, "special_manager");
			return (Criteria) this;
		}

		public Criteria andSpecial_managerLessThanOrEqualTo(String value) {
			addCriterion("special_manager <=", value, "special_manager");
			return (Criteria) this;
		}

		public Criteria andSpecial_managerLike(String value) {
			addCriterion("special_manager like", value, "special_manager");
			return (Criteria) this;
		}

		public Criteria andSpecial_managerNotLike(String value) {
			addCriterion("special_manager not like", value, "special_manager");
			return (Criteria) this;
		}

		public Criteria andSpecial_managerIn(List<String> values) {
			addCriterion("special_manager in", values, "special_manager");
			return (Criteria) this;
		}

		public Criteria andSpecial_managerNotIn(List<String> values) {
			addCriterion("special_manager not in", values, "special_manager");
			return (Criteria) this;
		}

		public Criteria andSpecial_managerBetween(String value1, String value2) {
			addCriterion("special_manager between", value1, value2, "special_manager");
			return (Criteria) this;
		}

		public Criteria andSpecial_managerNotBetween(String value1, String value2) {
			addCriterion("special_manager not between", value1, value2, "special_manager");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("phone is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("phone is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("phone =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("phone <>", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("phone >", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("phone >=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("phone <", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("phone <=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("phone like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("phone not like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneIn(List<String> values) {
			addCriterion("phone in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotIn(List<String> values) {
			addCriterion("phone not in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("phone between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("phone not between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andStop_timeIsNull() {
			addCriterion("stop_time is null");
			return (Criteria) this;
		}

		public Criteria andStop_timeIsNotNull() {
			addCriterion("stop_time is not null");
			return (Criteria) this;
		}

		public Criteria andStop_timeEqualTo(Date value) {
			addCriterion("stop_time =", value, "stop_time");
			return (Criteria) this;
		}

		public Criteria andStop_timeNotEqualTo(Date value) {
			addCriterion("stop_time <>", value, "stop_time");
			return (Criteria) this;
		}

		public Criteria andStop_timeGreaterThan(Date value) {
			addCriterion("stop_time >", value, "stop_time");
			return (Criteria) this;
		}

		public Criteria andStop_timeGreaterThanOrEqualTo(Date value) {
			addCriterion("stop_time >=", value, "stop_time");
			return (Criteria) this;
		}

		public Criteria andStop_timeLessThan(Date value) {
			addCriterion("stop_time <", value, "stop_time");
			return (Criteria) this;
		}

		public Criteria andStop_timeLessThanOrEqualTo(Date value) {
			addCriterion("stop_time <=", value, "stop_time");
			return (Criteria) this;
		}

		public Criteria andStop_timeIn(List<Date> values) {
			addCriterion("stop_time in", values, "stop_time");
			return (Criteria) this;
		}

		public Criteria andStop_timeNotIn(List<Date> values) {
			addCriterion("stop_time not in", values, "stop_time");
			return (Criteria) this;
		}

		public Criteria andStop_timeBetween(Date value1, Date value2) {
			addCriterion("stop_time between", value1, value2, "stop_time");
			return (Criteria) this;
		}

		public Criteria andStop_timeNotBetween(Date value1, Date value2) {
			addCriterion("stop_time not between", value1, value2, "stop_time");
			return (Criteria) this;
		}

		public Criteria andDelete_statusIsNull() {
			addCriterion("delete_status is null");
			return (Criteria) this;
		}

		public Criteria andDelete_statusIsNotNull() {
			addCriterion("delete_status is not null");
			return (Criteria) this;
		}

		public Criteria andDelete_statusEqualTo(Integer value) {
			addCriterion("delete_status =", value, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusNotEqualTo(Integer value) {
			addCriterion("delete_status <>", value, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusGreaterThan(Integer value) {
			addCriterion("delete_status >", value, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusGreaterThanOrEqualTo(Integer value) {
			addCriterion("delete_status >=", value, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusLessThan(Integer value) {
			addCriterion("delete_status <", value, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusLessThanOrEqualTo(Integer value) {
			addCriterion("delete_status <=", value, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusIn(List<Integer> values) {
			addCriterion("delete_status in", values, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusNotIn(List<Integer> values) {
			addCriterion("delete_status not in", values, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusBetween(Integer value1, Integer value2) {
			addCriterion("delete_status between", value1, value2, "delete_status");
			return (Criteria) this;
		}

		public Criteria andDelete_statusNotBetween(Integer value1, Integer value2) {
			addCriterion("delete_status not between", value1, value2, "delete_status");
			return (Criteria) this;
		}

		public Criteria andParent_idIsNull() {
			addCriterion("parent_id is null");
			return (Criteria) this;
		}

		public Criteria andParent_idIsNotNull() {
			addCriterion("parent_id is not null");
			return (Criteria) this;
		}

		public Criteria andParent_idEqualTo(Integer value) {
			addCriterion("parent_id =", value, "parent_id");
			return (Criteria) this;
		}

		public Criteria andParent_idNotEqualTo(Integer value) {
			addCriterion("parent_id <>", value, "parent_id");
			return (Criteria) this;
		}

		public Criteria andParent_idGreaterThan(Integer value) {
			addCriterion("parent_id >", value, "parent_id");
			return (Criteria) this;
		}

		public Criteria andParent_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("parent_id >=", value, "parent_id");
			return (Criteria) this;
		}

		public Criteria andParent_idLessThan(Integer value) {
			addCriterion("parent_id <", value, "parent_id");
			return (Criteria) this;
		}

		public Criteria andParent_idLessThanOrEqualTo(Integer value) {
			addCriterion("parent_id <=", value, "parent_id");
			return (Criteria) this;
		}

		public Criteria andParent_idIn(List<Integer> values) {
			addCriterion("parent_id in", values, "parent_id");
			return (Criteria) this;
		}

		public Criteria andParent_idNotIn(List<Integer> values) {
			addCriterion("parent_id not in", values, "parent_id");
			return (Criteria) this;
		}

		public Criteria andParent_idBetween(Integer value1, Integer value2) {
			addCriterion("parent_id between", value1, value2, "parent_id");
			return (Criteria) this;
		}

		public Criteria andParent_idNotBetween(Integer value1, Integer value2) {
			addCriterion("parent_id not between", value1, value2, "parent_id");
			return (Criteria) this;
		}

		public Criteria andIs_useIsNull() {
			addCriterion("is_use is null");
			return (Criteria) this;
		}

		public Criteria andIs_useIsNotNull() {
			addCriterion("is_use is not null");
			return (Criteria) this;
		}

		public Criteria andIs_useEqualTo(Integer value) {
			addCriterion("is_use =", value, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useNotEqualTo(Integer value) {
			addCriterion("is_use <>", value, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useGreaterThan(Integer value) {
			addCriterion("is_use >", value, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_use >=", value, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useLessThan(Integer value) {
			addCriterion("is_use <", value, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useLessThanOrEqualTo(Integer value) {
			addCriterion("is_use <=", value, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useIn(List<Integer> values) {
			addCriterion("is_use in", values, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useNotIn(List<Integer> values) {
			addCriterion("is_use not in", values, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useBetween(Integer value1, Integer value2) {
			addCriterion("is_use between", value1, value2, "is_use");
			return (Criteria) this;
		}

		public Criteria andIs_useNotBetween(Integer value1, Integer value2) {
			addCriterion("is_use not between", value1, value2, "is_use");
			return (Criteria) this;
		}

		public Criteria andUnit_competent_department_idIsNull() {
			addCriterion("unit_competent_department_id is null");
			return (Criteria) this;
		}

		public Criteria andUnit_competent_department_idIsNotNull() {
			addCriterion("unit_competent_department_id is not null");
			return (Criteria) this;
		}

		public Criteria andUnit_competent_department_idEqualTo(Integer value) {
			addCriterion("unit_competent_department_id =", value, "unit_competent_department_id");
			return (Criteria) this;
		}

		public Criteria andUnit_competent_department_idNotEqualTo(Integer value) {
			addCriterion("unit_competent_department_id <>", value, "unit_competent_department_id");
			return (Criteria) this;
		}

		public Criteria andUnit_competent_department_idGreaterThan(Integer value) {
			addCriterion("unit_competent_department_id >", value, "unit_competent_department_id");
			return (Criteria) this;
		}

		public Criteria andUnit_competent_department_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("unit_competent_department_id >=", value, "unit_competent_department_id");
			return (Criteria) this;
		}

		public Criteria andUnit_competent_department_idLessThan(Integer value) {
			addCriterion("unit_competent_department_id <", value, "unit_competent_department_id");
			return (Criteria) this;
		}

		public Criteria andUnit_competent_department_idLessThanOrEqualTo(Integer value) {
			addCriterion("unit_competent_department_id <=", value, "unit_competent_department_id");
			return (Criteria) this;
		}

		public Criteria andUnit_competent_department_idIn(List<Integer> values) {
			addCriterion("unit_competent_department_id in", values, "unit_competent_department_id");
			return (Criteria) this;
		}

		public Criteria andUnit_competent_department_idNotIn(List<Integer> values) {
			addCriterion("unit_competent_department_id not in", values, "unit_competent_department_id");
			return (Criteria) this;
		}

		public Criteria andUnit_competent_department_idBetween(Integer value1, Integer value2) {
			addCriterion("unit_competent_department_id between", value1, value2, "unit_competent_department_id");
			return (Criteria) this;
		}

		public Criteria andUnit_competent_department_idNotBetween(Integer value1, Integer value2) {
			addCriterion("unit_competent_department_id not between", value1, value2, "unit_competent_department_id");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_levy_fall
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_levy_fall
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 09 15:32:09 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}