package base.bill.entity;

import java.util.ArrayList;
import java.util.List;

public class TLevyfallBillInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public TLevyfallBillInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andLevyfall_bill_info_idIsNull() {
			addCriterion("levyfall_bill_info_id is null");
			return (Criteria) this;
		}

		public Criteria andLevyfall_bill_info_idIsNotNull() {
			addCriterion("levyfall_bill_info_id is not null");
			return (Criteria) this;
		}

		public Criteria andLevyfall_bill_info_idEqualTo(Integer value) {
			addCriterion("levyfall_bill_info_id =", value, "levyfall_bill_info_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_bill_info_idNotEqualTo(Integer value) {
			addCriterion("levyfall_bill_info_id <>", value, "levyfall_bill_info_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_bill_info_idGreaterThan(Integer value) {
			addCriterion("levyfall_bill_info_id >", value, "levyfall_bill_info_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_bill_info_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("levyfall_bill_info_id >=", value, "levyfall_bill_info_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_bill_info_idLessThan(Integer value) {
			addCriterion("levyfall_bill_info_id <", value, "levyfall_bill_info_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_bill_info_idLessThanOrEqualTo(Integer value) {
			addCriterion("levyfall_bill_info_id <=", value, "levyfall_bill_info_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_bill_info_idIn(List<Integer> values) {
			addCriterion("levyfall_bill_info_id in", values, "levyfall_bill_info_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_bill_info_idNotIn(List<Integer> values) {
			addCriterion("levyfall_bill_info_id not in", values, "levyfall_bill_info_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_bill_info_idBetween(Integer value1, Integer value2) {
			addCriterion("levyfall_bill_info_id between", value1, value2, "levyfall_bill_info_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_bill_info_idNotBetween(Integer value1, Integer value2) {
			addCriterion("levyfall_bill_info_id not between", value1, value2, "levyfall_bill_info_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idIsNull() {
			addCriterion("levyfall_id is null");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idIsNotNull() {
			addCriterion("levyfall_id is not null");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idEqualTo(Integer value) {
			addCriterion("levyfall_id =", value, "levyfall_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idNotEqualTo(Integer value) {
			addCriterion("levyfall_id <>", value, "levyfall_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idGreaterThan(Integer value) {
			addCriterion("levyfall_id >", value, "levyfall_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("levyfall_id >=", value, "levyfall_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idLessThan(Integer value) {
			addCriterion("levyfall_id <", value, "levyfall_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idLessThanOrEqualTo(Integer value) {
			addCriterion("levyfall_id <=", value, "levyfall_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idIn(List<Integer> values) {
			addCriterion("levyfall_id in", values, "levyfall_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idNotIn(List<Integer> values) {
			addCriterion("levyfall_id not in", values, "levyfall_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idBetween(Integer value1, Integer value2) {
			addCriterion("levyfall_id between", value1, value2, "levyfall_id");
			return (Criteria) this;
		}

		public Criteria andLevyfall_idNotBetween(Integer value1, Integer value2) {
			addCriterion("levyfall_id not between", value1, value2, "levyfall_id");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idIsNull() {
			addCriterion("bill_info_maintain_id is null");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idIsNotNull() {
			addCriterion("bill_info_maintain_id is not null");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idEqualTo(Integer value) {
			addCriterion("bill_info_maintain_id =", value, "bill_info_maintain_id");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idNotEqualTo(Integer value) {
			addCriterion("bill_info_maintain_id <>", value, "bill_info_maintain_id");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idGreaterThan(Integer value) {
			addCriterion("bill_info_maintain_id >", value, "bill_info_maintain_id");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("bill_info_maintain_id >=", value, "bill_info_maintain_id");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idLessThan(Integer value) {
			addCriterion("bill_info_maintain_id <", value, "bill_info_maintain_id");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idLessThanOrEqualTo(Integer value) {
			addCriterion("bill_info_maintain_id <=", value, "bill_info_maintain_id");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idIn(List<Integer> values) {
			addCriterion("bill_info_maintain_id in", values, "bill_info_maintain_id");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idNotIn(List<Integer> values) {
			addCriterion("bill_info_maintain_id not in", values, "bill_info_maintain_id");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idBetween(Integer value1, Integer value2) {
			addCriterion("bill_info_maintain_id between", value1, value2, "bill_info_maintain_id");
			return (Criteria) this;
		}

		public Criteria andBill_info_maintain_idNotBetween(Integer value1, Integer value2) {
			addCriterion("bill_info_maintain_id not between", value1, value2, "bill_info_maintain_id");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_levyfall_bill_info
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_levyfall_bill_info
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 09 15:32:09 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}