package base.bill.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.jeecgframework.poi.excel.annotation.Excel;
import org.jeecgframework.poi.excel.annotation.ExcelEntity;
import org.jeecgframework.poi.excel.annotation.ExcelTarget;

import base.bill.entity.TBudgetKindMoney;
import base.bill.entity.TNotaxProject;

import io.swagger.annotations.ApiModelProperty;
@ExcelTarget(value = "notaxProject")
public class TNotaxProject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.notax_project_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer notax_project_id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.non_taxproject_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "项目编码", mergeVertical = true, isImportField = "non_taxproject_code")
	private String non_taxproject_code;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.non_taxproject_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "项目名称", mergeVertical = true, isImportField = "non_taxproject_name")
	private String non_taxproject_name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.unit_competent_department_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "主管部门", mergeVertical = true, isImportField = "unit_competent_department_id")
	private Integer unit_competent_department_id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.flag
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "特殊标志", mergeVertical = true, isImportField = "flag")
	private Integer flag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.manage_mode
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "管理模式", mergeVertical = true, isImportField = "manage_mode")
	private Integer manage_mode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.collection_object
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "征收对象", mergeVertical = true, isImportField = "collection_object")
	private String collection_object;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.isdivide_into
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "是否分成", mergeVertical = true, isImportField = "isdivide_into")
	private Integer isdivide_into;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.divide_mode
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "分成方式", mergeVertical = true, isImportField = "divide_mode")
	private Integer divide_mode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.upper_limit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "标准上限", mergeVertical = true, isImportField = "upper_limit")
	private Integer upper_limit;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.is_upper_limit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer is_upper_limit;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.lower_limit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "标准下限", mergeVertical = true, isImportField = "lower_limit")
	private Integer lower_limit;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.measurement_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "计量单位", mergeVertical = true, isImportField = "measurement_unit")
	private String measurement_unit;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.center_divide_into
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "中央分成", mergeVertical = true, isImportField = "center_divide_into")
	private Integer center_divide_into;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.provincial_level_divideinto
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "省级分成", mergeVertical = true, isImportField = "provincial_level_divideinto")
	private Integer provincial_level_divideinto;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.city_level_divideInto
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "市级分成", mergeVertical = true, isImportField = "city_level_divideInto")
	private Integer city_level_divideInto;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.county_level_divideinto
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "县级分成", mergeVertical = true, isImportField = "county_level_divideinto")
	private Integer county_level_divideinto;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.standard_filename
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "标准文件名称", mergeVertical = true, isImportField = "standard_filename")
	private String standard_filename;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.project_filename
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "立项文件名称", mergeVertical = true, isImportField = "project_filename")
	private String project_filename;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.create_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Date create_time;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.stop_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Date stop_time;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.parent_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer parent_id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.is_use
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer is_use;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.remark
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	@Excel(name = "备注", mergeVertical = true, isImportField = "remark")
	private String remark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer delete_status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notax_project.budget_kind_money_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	private Integer budget_kind_money_id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.notax_project_id
	 * @return  the value of t_notax_project.notax_project_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getNotax_project_id() {
		return notax_project_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.notax_project_id
	 * @param notax_project_id  the value for t_notax_project.notax_project_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setNotax_project_id(Integer notax_project_id) {
		this.notax_project_id = notax_project_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.non_taxproject_code
	 * @return  the value of t_notax_project.non_taxproject_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getNon_taxproject_code() {
		return non_taxproject_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.non_taxproject_code
	 * @param non_taxproject_code  the value for t_notax_project.non_taxproject_code
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setNon_taxproject_code(String non_taxproject_code) {
		this.non_taxproject_code = non_taxproject_code == null ? null : non_taxproject_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.non_taxproject_name
	 * @return  the value of t_notax_project.non_taxproject_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getNon_taxproject_name() {
		return non_taxproject_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.non_taxproject_name
	 * @param non_taxproject_name  the value for t_notax_project.non_taxproject_name
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setNon_taxproject_name(String non_taxproject_name) {
		this.non_taxproject_name = non_taxproject_name == null ? null : non_taxproject_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.unit_competent_department_id
	 * @return  the value of t_notax_project.unit_competent_department_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getUnit_competent_department_id() {
		return unit_competent_department_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.unit_competent_department_id
	 * @param unit_competent_department_id  the value for t_notax_project.unit_competent_department_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setUnit_competent_department_id(Integer unit_competent_department_id) {
		this.unit_competent_department_id = unit_competent_department_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.flag
	 * @return  the value of t_notax_project.flag
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getFlag() {
		return flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.flag
	 * @param flag  the value for t_notax_project.flag
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.manage_mode
	 * @return  the value of t_notax_project.manage_mode
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getManage_mode() {
		return manage_mode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.manage_mode
	 * @param manage_mode  the value for t_notax_project.manage_mode
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setManage_mode(Integer manage_mode) {
		this.manage_mode = manage_mode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.collection_object
	 * @return  the value of t_notax_project.collection_object
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getCollection_object() {
		return collection_object;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.collection_object
	 * @param collection_object  the value for t_notax_project.collection_object
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCollection_object(String collection_object) {
		this.collection_object = collection_object == null ? null : collection_object.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.isdivide_into
	 * @return  the value of t_notax_project.isdivide_into
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getIsdivide_into() {
		return isdivide_into;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.isdivide_into
	 * @param isdivide_into  the value for t_notax_project.isdivide_into
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setIsdivide_into(Integer isdivide_into) {
		this.isdivide_into = isdivide_into;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.divide_mode
	 * @return  the value of t_notax_project.divide_mode
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getDivide_mode() {
		return divide_mode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.divide_mode
	 * @param divide_mode  the value for t_notax_project.divide_mode
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setDivide_mode(Integer divide_mode) {
		this.divide_mode = divide_mode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.upper_limit
	 * @return  the value of t_notax_project.upper_limit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getUpper_limit() {
		return upper_limit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.upper_limit
	 * @param upper_limit  the value for t_notax_project.upper_limit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setUpper_limit(Integer upper_limit) {
		this.upper_limit = upper_limit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.is_upper_limit
	 * @return  the value of t_notax_project.is_upper_limit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getIs_upper_limit() {
		return is_upper_limit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.is_upper_limit
	 * @param is_upper_limit  the value for t_notax_project.is_upper_limit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setIs_upper_limit(Integer is_upper_limit) {
		this.is_upper_limit = is_upper_limit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.lower_limit
	 * @return  the value of t_notax_project.lower_limit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getLower_limit() {
		return lower_limit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.lower_limit
	 * @param lower_limit  the value for t_notax_project.lower_limit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setLower_limit(Integer lower_limit) {
		this.lower_limit = lower_limit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.measurement_unit
	 * @return  the value of t_notax_project.measurement_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getMeasurement_unit() {
		return measurement_unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.measurement_unit
	 * @param measurement_unit  the value for t_notax_project.measurement_unit
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setMeasurement_unit(String measurement_unit) {
		this.measurement_unit = measurement_unit == null ? null : measurement_unit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.center_divide_into
	 * @return  the value of t_notax_project.center_divide_into
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getCenter_divide_into() {
		return center_divide_into;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.center_divide_into
	 * @param center_divide_into  the value for t_notax_project.center_divide_into
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCenter_divide_into(Integer center_divide_into) {
		this.center_divide_into = center_divide_into;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.provincial_level_divideinto
	 * @return  the value of t_notax_project.provincial_level_divideinto
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getProvincial_level_divideinto() {
		return provincial_level_divideinto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.provincial_level_divideinto
	 * @param provincial_level_divideinto  the value for t_notax_project.provincial_level_divideinto
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setProvincial_level_divideinto(Integer provincial_level_divideinto) {
		this.provincial_level_divideinto = provincial_level_divideinto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.city_level_divideInto
	 * @return  the value of t_notax_project.city_level_divideInto
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getCity_level_divideInto() {
		return city_level_divideInto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.city_level_divideInto
	 * @param city_level_divideInto  the value for t_notax_project.city_level_divideInto
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCity_level_divideInto(Integer city_level_divideInto) {
		this.city_level_divideInto = city_level_divideInto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.county_level_divideinto
	 * @return  the value of t_notax_project.county_level_divideinto
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getCounty_level_divideinto() {
		return county_level_divideinto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.county_level_divideinto
	 * @param county_level_divideinto  the value for t_notax_project.county_level_divideinto
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCounty_level_divideinto(Integer county_level_divideinto) {
		this.county_level_divideinto = county_level_divideinto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.standard_filename
	 * @return  the value of t_notax_project.standard_filename
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getStandard_filename() {
		return standard_filename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.standard_filename
	 * @param standard_filename  the value for t_notax_project.standard_filename
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setStandard_filename(String standard_filename) {
		this.standard_filename = standard_filename == null ? null : standard_filename.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.project_filename
	 * @return  the value of t_notax_project.project_filename
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getProject_filename() {
		return project_filename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.project_filename
	 * @param project_filename  the value for t_notax_project.project_filename
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setProject_filename(String project_filename) {
		this.project_filename = project_filename == null ? null : project_filename.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.create_time
	 * @return  the value of t_notax_project.create_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getCreate_time() {
		return create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.create_time
	 * @param create_time  the value for t_notax_project.create_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.stop_time
	 * @return  the value of t_notax_project.stop_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Date getStop_time() {
		return stop_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.stop_time
	 * @param stop_time  the value for t_notax_project.stop_time
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setStop_time(Date stop_time) {
		this.stop_time = stop_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.parent_id
	 * @return  the value of t_notax_project.parent_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getParent_id() {
		return parent_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.parent_id
	 * @param parent_id  the value for t_notax_project.parent_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setParent_id(Integer parent_id) {
		this.parent_id = parent_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.is_use
	 * @return  the value of t_notax_project.is_use
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getIs_use() {
		return is_use;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.is_use
	 * @param is_use  the value for t_notax_project.is_use
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setIs_use(Integer is_use) {
		this.is_use = is_use;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.remark
	 * @return  the value of t_notax_project.remark
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.remark
	 * @param remark  the value for t_notax_project.remark
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.delete_status
	 * @return  the value of t_notax_project.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getDelete_status() {
		return delete_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.delete_status
	 * @param delete_status  the value for t_notax_project.delete_status
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setDelete_status(Integer delete_status) {
		this.delete_status = delete_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notax_project.budget_kind_money_id
	 * @return  the value of t_notax_project.budget_kind_money_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public Integer getBudget_kind_money_id() {
		return budget_kind_money_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notax_project.budget_kind_money_id
	 * @param budget_kind_money_id  the value for t_notax_project.budget_kind_money_id
	 * @mbg.generated  Wed Sep 05 10:25:24 CST 2018
	 */
	public void setBudget_kind_money_id(Integer budget_kind_money_id) {
		this.budget_kind_money_id = budget_kind_money_id;
	}

	@ExcelEntity(name = "tBudgetKindMoney")
	private TBudgetKindMoney tBudgetKindMoney;
	
	@ApiModelProperty(value = "是否选中")
	private boolean status;

	public boolean isStatus() {
		return status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	private List<TNotaxProject> children = new ArrayList<TNotaxProject>();
	
	public List<TNotaxProject> getChildren() {
		return children;
	}

	public void setChildren(List<TNotaxProject> children) {
		this.children = children;
	}

	public TBudgetKindMoney gettBudgetKindMoney() {
		return tBudgetKindMoney;
	}

	public void settBudgetKindMoney(TBudgetKindMoney tBudgetKindMoney) {
		this.tBudgetKindMoney = tBudgetKindMoney;
	}

	public String getCode_name() {
		return code_name;
	}

	public void setCode_name(String code_name) {
		this.code_name = code_name;
	}
	
	public boolean isLoading() {
		return loading;
	}

	public void setLoading(boolean loading) {
		this.loading = loading;
	}

	public Integer getCapital_property() {
		return capital_property;
	}

	public void setCapital_property(Integer capital_property) {
		this.capital_property = capital_property;
	}

	public boolean isDisabled() {
		return disabled;
	}

	public void setDisabled(boolean disabled) {
		this.disabled = disabled;
	}

	@ApiModelProperty(value = "非税code和name拼接")
	private String code_name;
	
	@ApiModelProperty(value = "是否加载")
	private boolean loading;
	
	@ApiModelProperty(value = "资质性质")
	private Integer capital_property;
	
	@ApiModelProperty()
	private boolean disabled;
}