package com.usersauth.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.usersauth.entity.SysPermission;
import com.usersauth.entity.SysPermissionExample;
import com.usersauth.vo.SysPermissionVO;

public interface SysPermissionMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	long countByExample(SysPermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	int deleteByExample(SysPermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	int insert(SysPermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	int insertSelective(SysPermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	List<SysPermission> selectByExample(SysPermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	SysPermission selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	int updateByExampleSelective(@Param("record") SysPermission record, @Param("example") SysPermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	int updateByExample(@Param("record") SysPermission record, @Param("example") SysPermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	int updateByPrimaryKeySelective(SysPermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Fri Aug 17 09:38:07 CST 2018
	 */
	int updateByPrimaryKey(SysPermission record);

	/**
	 * 
	 * @描述:根据用户查询权限
	 * @方法名: listSysPermissionBySysUserID
	 * @param userid
	 * @return
	 * @返回类型 List<SysPermission>
	 * @创建人 王靓
	 * @创建时间 2018年6月1日上午9:29:46
	 * @修改人 王靓
	 * @修改时间 2018年6月1日上午9:29:46
	 * @修改备注
	 * @since
	 * @throws
	 */
	List<SysPermission> listSysPermissionBySysUserID(Integer userid);
	
	/**
	 * 
	 * @描述:根据父级查询权限
	 * @方法名: listSysPermissionByParentId
	 * @param parent_id
	 * @return
	 * @返回类型 List<SysPermissionVO>
	 * @创建人 王靓
	 * @创建时间 2018年6月1日上午9:30:52
	 * @修改人 王靓
	 * @修改时间 2018年6月1日上午9:30:52
	 * @修改备注
	 * @since
	 * @throws
	 */
	List<SysPermissionVO> listSysPermissionByParentId(Integer parent_id);
	/**
	 * 
	 * @描述:根据父级查询权限
	 * @方法名: listSysPermissionByParentIdAndServiceToken
	 * @param parent_id,service_token
	 * @return
	 * @返回类型 List<SysPermissionVO>
	 * @创建人 王靓
	 * @创建时间 2018年8月17日上午11:30:52
	 * @修改人 王靓
	 * @修改时间 2018年8月17日上午11:30:52
	 * @修改备注
	 * @since
	 * @throws
	 */
	List<SysPermissionVO> listSysPermissionByParentIdAndServiceToken(@Param("parent_id")Integer parent_id,@Param("service_token")String service_token);
	
	/**
	 * 
	 * @描述:根据父级和角色查询权限
	 * @方法名: listSysPermissionVOByParentIdAndRoleID
	 * @param record
	 * @return
	 * @返回类型 List<SysPermissionVO>
	 * @创建人 王靓
	 * @创建时间 2018年6月1日上午9:30:55
	 * @修改人 王靓
	 * @修改时间 2018年6月1日上午9:30:55
	 * @修改备注
	 * @since
	 * @throws
	 */
	List<SysPermissionVO> listSysPermissionVOByParentIdAndRoleID(SysPermissionVO record);
}